import { useEffect, useRef, useState } from 'react';
import { post, request } from '../../api';
import { Badge, Detail, Field, Notice } from '../../components';
import { formatDate, isRunning, messageOf, statusLabel } from '../../utils';
import { assessmentPayload, emptyAssessment, RevisionAssessmentDetails, RevisionAssessmentEditor, RevisionComparisonDetails, type EditableAssessment } from './AnalysisAdjudication';
import type { AnalysisRecord } from './analysisTypes';
import { ARM_LABELS, type ComparisonArm, type ComparisonCapture, type ComparisonEffort, type RegistrationContext } from './comparisonTypes';

const ARMS = Object.keys(ARM_LABELS) as ComparisonArm[];
const seconds = (value: number | null) => value === null ? 'Ölçülmedi' : `${value.toFixed(3)} sn`;
export function effortPayload(values: Record<ComparisonArm, string[]>) {
  const arms = ARMS.map((arm) => { const [preparation_seconds, verification_seconds, correction_seconds] = values[arm].map((value) => value.trim() === '' ? null : Number(value)); return { arm, preparation_seconds, verification_seconds, correction_seconds }; });
  return arms.some((item) => [item.preparation_seconds, item.verification_seconds, item.correction_seconds].some((value) => value !== null && (!Number.isInteger(value) || value < 0 || value > 28800))) ? null : arms;
}
export function ComparisonSummary({ value }: { value: ComparisonCapture }) {
  return <><div className="practice-record-heading"><strong>{value.protocol.title}</strong><Badge>{value.freshness.status === 'stale' ? 'Deneme güncel değil' : value.capture_complete ? 'Karşılaştırma kaydı tamamlandı' : 'Karşılaştırma kaydı eksik'}</Badge></div><p>{value.current_reviewer_count}/2 atanmış inceleyen · Aktif çalışma hesabı {value.effort_accounted ? 'kaydedildi' : 'eksik'} · {value.sample_kind === 'synthetic' ? 'Kurgusal örnek' : 'Gerçek örnek beyanı'}</p><p className="small muted">Geliştirme karşılaştırmasıdır. Kayıt tamamlanması hukuki doğruluk, bağımsız uzmanlık veya model faydasını kanıtlamaz. Adaylar çalışma taslağına uygulanmaz.</p>{value.protocol.provider_pin.transport?.uses_public_network && <p className="small muted">Onaylı dizüstü tüneli internet üzerinden yerel modele erişir; bu aktarım air-gapped değildir.</p>}{value.freshness.status === 'stale' && <Notice error>{value.freshness.reasons.join(' ')}</Notice>}<Detail title="Sabit soru, ölçütler ve kapsam"><p className="authored-text">{value.protocol.question}</p><p className="authored-text">{value.protocol.rubric_text}</p><p>Kaynak sürüm {value.protocol.source_version} · Yerel model: {value.protocol.provider_pin.model} · Kayıt: {formatDate(value.protocol.registered_at, true)}</p><p>Her kol aynı özel taslaktan başlar. Ek geçiş yalnız kritik yapısal kontrol kalırsa yapılır; daha derin hukuki araştırma olarak değerlendirilmez. Kamu/karşı içtihat araştırması bu denemede yoktur.</p><p className="reference-id">Protokol: {value.protocol.protocol_sha256} · Girdi: {value.protocol.task_input_sha256} · Çalıştırma: {value.execution_sha256}</p></Detail></>;
}

export function ComparisonEffortForm({ value, busy, onSave }: { value: ComparisonCapture; busy: boolean; onSave: (body: object) => void }) {
  const [times, setTimes] = useState<Record<ComparisonArm, string[]>>({ single_pass: ['', '', ''], bounded_correction: ['', '', ''] });
  const [setup, setSetup] = useState(false); const [included, setIncluded] = useState(false); const [note, setNote] = useState('');
  const arms = effortPayload(times);
  return <Detail title="Aktif çalışma süresini kaydet"><form onSubmit={(event) => { event.preventDefault(); if (arms) onSave({ arms, note, shared_setup_included: setup, verification_and_correction_included: included, execution_sha256: value.execution_sha256, expected_previous_id: value.previous_effort_id }); }}><p>Model bekleme süresini eklemeyin. Hazırlık, özgün kaynak doğrulama/avukat incelemesi ve düzeltme süreleri çakışmayan aktif çalışma bileşenleridir. Ortak hazırlığı her iki kola aynı biçimde dahil edin. Bağımsız değerlendirme ekibinin gözlem süresi ayrıca tutulur.</p>{ARMS.map((arm) => <Detail key={arm} title={ARM_LABELS[arm]}>{['Hazırlık', 'Doğrulama ve inceleme', 'Düzeltme'].map((label, index) => <Field key={label} label={`${ARM_LABELS[arm]} · ${label} (sn)`} hint="Boş: bilinmiyor. Sıfır yalnız gerçekten süre harcanmadığında.">{(id) => <input id={id} type="number" min={0} max={28800} step={1} value={times[arm][index]} disabled={busy} onChange={(event) => setTimes((old) => ({ ...old, [arm]: old[arm].map((time, i) => i === index ? event.target.value : time) }))} />}</Field>)}</Detail>)}<label><input type="checkbox" checked={setup} disabled={busy} onChange={(event) => setSetup(event.target.checked)} />Ortak hazırlık iki kola aynı biçimde dahil edildi</label><label><input type="checkbox" checked={included} disabled={busy} onChange={(event) => setIncluded(event.target.checked)} />Tüm doğrulama, avukat incelemesi ve düzeltme çalışması dahil edildi</label><Field label="Süre kaydının açıklaması">{(id) => <textarea id={id} value={note} rows={2} maxLength={2000} disabled={busy} onChange={(event) => setNote(event.target.value)} />}</Field><button type="submit" className="button secondary" disabled={busy || !arms || note.trim().length < 3}>Süre beyanını kaydet</button><p className="small muted">Eksik bileşen bilinmiyor olarak kalır; süre kazanımı hesaplanmaz. Önceki kayıt korunur.</p></form></Detail>;
}

export function ObservationForm({ value, busy, onSource, onSave }: { value: ComparisonCapture; busy: boolean; onSource: (id: string) => void; onSave: (body: object) => void }) {
  const [assessments, setAssessments] = useState<Record<ComparisonArm, EditableAssessment>>(() => Object.fromEntries(ARMS.map((arm) => [arm, emptyAssessment(value.arms[arm].comparison!)])) as Record<ComparisonArm, EditableAssessment>);
  const [note, setNote] = useState('');
  const arms = ARMS.map((arm) => ({ arm, assessment: assessmentPayload(assessments[arm], value.arms[arm].comparison!) }));
  return <Detail title="Atanmış inceleyen gözlemini kaydet"><form onSubmit={(event) => { event.preventDefault(); if (arms.every((item) => item.assessment)) onSave({ arms, note, execution_sha256: value.execution_sha256, expected_previous_id: value.previous_observation_id }); }}><p>Her iki kolu sabit ölçütlerle ayrı inceleyin. Diğer inceleyenin kaydı yerine kendi değerlendirmenizi yazın. Bu ekran kör değerlendirme sağlamaz; hesap ayrımı uzmanlık veya fiili bağımsızlık belgesi değildir.</p>{ARMS.map((arm) => <Detail key={arm} title={`${ARM_LABELS[arm]} · Kaynak bağlı değerlendirme`}><RevisionComparisonDetails comparison={value.arms[arm].comparison!} onSource={onSource} /><RevisionAssessmentEditor comparison={value.arms[arm].comparison!} value={assessments[arm]} onChange={(next) => setAssessments((old) => ({ ...old, [arm]: next }))} busy={busy} /></Detail>)}<Field label="Karşılaştırma gözleminin açıklaması">{(id) => <textarea id={id} rows={2} maxLength={2000} value={note} disabled={busy} onChange={(event) => setNote(event.target.value)} />}</Field><button type="submit" className="button secondary" disabled={busy || note.trim().length < 3 || arms.some((item) => !item.assessment)}>Kendi gözlemimi kaydet</button><p className="small muted">Çözülmemiş veya değerlendirilmemiş konular açık kalır; kayıt mevcut taslağın avukat inceleme kararını değiştirmez.</p></form></Detail>;
}

function TimingDetails({ values }: { values: ComparisonEffort[] }) {
  return <>{values.map((item) => <p key={item.arm}>{ARM_LABELS[item.arm]} · Hazırlık: {seconds(item.preparation_seconds)} · Doğrulama/inceleme: {seconds(item.verification_seconds)} · Düzeltme: {seconds(item.correction_seconds)}</p>)}</>;
}
export function ComparisonResults({ value, onSource }: { value: Pick<ComparisonCapture, 'protocol' | 'arms' | 'observations' | 'effort_history'>; onSource: (id: string) => void }) {
  return <>{ARMS.map((arm) => { const item = value.arms[arm]; return <Detail key={arm} title={`${ARM_LABELS[arm]} · ${item.status === 'not_started' ? 'Başlatılmadı' : statusLabel(item.status)}`}><p>{item.job?.iterations?.length ?? 0} saklanan geçiş · Üst sınır {value.protocol.arms[arm].max_passes} geçiş / {value.protocol.arms[arm].budget_seconds} sn</p><p>İşin duvar saati (kuyruk dahil): {seconds(item.elapsed_seconds)} · Sağlayıcı gidiş/dönüşü: {seconds(item.provider_round_trip_seconds)} · GPU hesap süresi: Ölçülmedi</p>{item.job?.error && <p className="authored-text">{item.job.error}</p>}<p className="small muted">Eksik/başarısız çalışmada toplam çağrı maliyeti bilinmiyor; saklanan geçişler bütün denemelerin sayısı sayılmaz.</p>{item.comparison && <RevisionComparisonDetails comparison={item.comparison} onSource={onSource} />}</Detail>; })}<Detail title={`İnceleyen gözlem geçmişi (${value.observations.length})`}>{value.observations.map((event) => <Detail key={event.id} title={`${event.reviewer_name} · Gözlem ${event.sequence}`}><p className="authored-text">{event.note}</p>{event.arms.map((item) => <Detail key={item.arm} title={ARM_LABELS[item.arm]}><RevisionAssessmentDetails assessment={item.assessment} comparison={event.comparison_snapshots[item.arm]} onSource={onSource} /></Detail>)}</Detail>)}</Detail><Detail title={`Aktif çalışma geçmişi (${value.effort_history.length})`}>{value.effort_history.map((event) => <Detail key={event.id} title={`${event.reviewer_name} · Süre kaydı ${event.sequence}`}><p className="authored-text">{event.note}</p><TimingDetails values={event.arms} /><p>Ortak hazırlık: {event.shared_setup_included ? 'Dahil beyanı' : 'Dahil olduğu doğrulanmadı'} · Doğrulama/düzeltme: {event.verification_and_correction_included ? 'Dahil beyanı' : 'Dahil olduğu doğrulanmadı'}</p></Detail>)}</Detail></>;
}

function ComparisonCard({ id, title, base, suggestionBase, onSource }: { id: string; title: string; base: string; suggestionBase: string; onSource: (id: string) => void }) {
  const [value, setValue] = useState<ComparisonCapture | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const pending = useRef<{ key: string; id: string } | null>(null); const endpoint = `${base}/${encodeURIComponent(id)}`;
  const active = !!value && ARMS.some((arm) => isRunning(value.arms[arm].status));
  useEffect(() => { if (!active) return; const controller = new AbortController(); let polling = false; let failures = 0; const timer = window.setInterval(async () => { if (polling) return; polling = true; try { const next = await request<ComparisonCapture>(endpoint, { signal: controller.signal }); if (!controller.signal.aborted) { setValue(next); setError(''); failures = 0; } } catch (cause) { if (!controller.signal.aborted) { setError(messageOf(cause)); if (++failures >= 3) window.clearInterval(timer); } } finally { polling = false; } }, 2500); return () => { controller.abort(); window.clearInterval(timer); }; }, [active, endpoint]);
  async function refresh() { setBusy(true); setError(''); try { setValue(await request<ComparisonCapture>(endpoint)); } catch (cause) { setValue(null); setError(messageOf(cause)); } finally { setBusy(false); } }
  async function run() { setBusy(true); setError(''); try { setValue(await post<ComparisonCapture>(`${endpoint}/run`, {})); } catch (cause) { setError(messageOf(cause)); try { setValue(await request<ComparisonCapture>(endpoint)); } catch { setValue(null); } } finally { setBusy(false); } }
  async function save(kind: 'observations' | 'effort', body: object) { setBusy(true); setError(''); const key = kind + JSON.stringify(body); if (pending.current?.key !== key) pending.current = { key, id: crypto.randomUUID().replaceAll('-', '') }; try { await post(`${endpoint}/${kind}`, { ...body, request_id: pending.current.id }); pending.current = null; setValue(await request<ComparisonCapture>(endpoint)); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  async function stop(jobId: string) { setBusy(true); setError(''); try { await post(`${suggestionBase}/${encodeURIComponent(jobId)}/cancel`, {}); setValue(await request<ComparisonCapture>(endpoint)); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }

  return <Detail title={title}><button className="text-button" disabled={busy} onClick={() => void refresh()}>{value ? 'Deneme durumunu yenile' : 'Denemeyi aç'}</button>{value && <><ComparisonSummary value={value} /><div className="practice-record-actions">{value.can_run && <button className="button secondary" disabled={busy} onClick={() => void run()}>Kayıtlı iki kolu yerel modelde çalıştır</button>}<a className="text-button" href={busy ? undefined : `/api/v1${endpoint}/export`} aria-disabled={busy} download>Özel deneme kaydını indir</a></div>{value.can_run && <p className="small muted">Her kol en fazla {value.protocol.arms.single_pass.budget_seconds}/{value.protocol.arms.bounded_correction.budget_seconds} sn; toplam en fazla üç model çağrısı. Sadece başlatılmamış kol çalıştırılır; durmuş kol tekrar çağrılmaz.</p>}{ARMS.map((arm) => value.arms[arm].job && isRunning(value.arms[arm].status) && <button key={arm} className="text-button" disabled={busy || value.arms[arm].status === 'cancelling'} onClick={() => void stop(value.arms[arm].job!.id)}>{ARM_LABELS[arm]} · Durdur</button>)}<ComparisonResults value={value} onSource={onSource} />{value.can_record_effort && <ComparisonEffortForm key={`${value.execution_sha256}:${value.previous_effort_id}`} value={value} busy={busy} onSave={(body) => void save('effort', body)} />}{value.can_observe && <ObservationForm key={`${value.execution_sha256}:${value.previous_observation_id}`} value={value} busy={busy} onSource={onSource} onSave={(body) => void save('observations', body)} />}</>}{error && <Notice error>{error}</Notice>}</Detail>;
}

export function RegistrationForm({ context, busy, onSave }: { context: RegistrationContext; busy: boolean; onSave: (body: object, family: string) => void }) {
  const [title, setTitle] = useState(''); const [question, setQuestion] = useState(''); const [rubric, setRubric] = useState(''); const [family, setFamily] = useState(''); const [sample, setSample] = useState<'real' | 'synthetic' | ''>(''); const [reviewers, setReviewers] = useState<string[]>([]);
  return <form onSubmit={(event) => { event.preventDefault(); onSave({ title, question, rubric_text: rubric, sample_kind: sample, reviewer_ids: reviewers, expected_revision: context.expected_revision, version_id: context.version_id, context_sha256: context.context_sha256 }, family); }}><p>Mevcut özel taslak, inceleme, model, ölçütler ve bütçeler iki kol başlamadan sabitlenir. Bu kayıt sürüm yayını veya hukuki kullanım izni değildir.</p>{[['Deneme başlığı', title, setTitle], ['Karşılaştırma sorusu', question, setQuestion], ['Örnek ailesi', family, setFamily]] .map(([label, text, setter]) => <Field key={label as string} label={label as string}>{(id) => <input id={id} value={text as string} maxLength={label === 'Karşılaştırma sorusu' ? 2000 : 200} disabled={busy} onChange={(event) => (setter as (value: string) => void)(event.target.value)} />}</Field>)}<p className="small muted">Örnek ailesi aynı belge/dosya ve yakın benzer örnekleri birlikte tutmak için sizin tanımladığınız gruptur; sistem bağımsızlığı veya sızıntı olmadığını doğrulamaz.</p><Field label="Değerlendirme ölçütleri">{(id) => <textarea id={id} rows={4} maxLength={12000} value={rubric} disabled={busy} onChange={(event) => setRubric(event.target.value)} />}</Field><Field label="Örnek türü">{(id) => <select id={id} value={sample} disabled={busy} onChange={(event) => setSample(event.target.value as typeof sample)}><option value="">Örnek türünü seçin</option><option value="synthetic">Kurgusal geliştirme örneği</option>{!context.synthetic_only && <option value="real">Gerçek özel çalışma · kapsam onayı verilmez</option>}</select>}</Field><fieldset disabled={busy}><legend>İki farklı mevcut inceleyen</legend>{context.eligible_reviewers.map((item) => <label key={item.id}><input type="checkbox" checked={reviewers.includes(item.id)} disabled={busy || (!reviewers.includes(item.id) && reviewers.length === 2)} onChange={(event) => setReviewers((old) => event.target.checked ? [...old, item.id] : old.filter((id) => id !== item.id))} />{item.name}</label>)}</fieldset>{!context.can_register && <p>Güncel kaynaklı taslak, doğrulanmış yerel model yapılandırması ve en az iki farklı mevcut dosya üyesi gerekli. Taslak yazarı, önceki inceleyen ve deneme sahibi gözlemci atanamaz.</p>}<button className="button secondary" type="submit" disabled={busy || !context.can_register || !sample || reviewers.length !== 2 || [title, question, rubric, family].some((text) => text.trim().length < 3)}>Protokolü sabitle · Henüz model çağrılmaz</button></form>;
}

export function AnalysisComparisons({ matterId, record, onSource }: { matterId: string; record: AnalysisRecord; onSource: (id: string) => void }) {
  const base = `/matters/${encodeURIComponent(matterId)}/analyses/${encodeURIComponent(record.id)}/comparisons`;
  const suggestionBase = base.replace(/comparisons$/, 'suggestions');
  const [items, setItems] = useState<{ id: string; title: string }[]>([]); const [context, setContext] = useState<RegistrationContext | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [loaded, setLoaded] = useState(false); const [more, setMore] = useState(false);
  const pending = useRef<{ key: string; id: string } | null>(null);
  async function history(append = false) { setBusy(true); setError(''); try { const page = await request<{ id: string; title: string }[]>(`${base}?limit=10&offset=${append ? items.length : 0}`); setItems((old) => append ? [...old, ...page.filter((item) => !old.some((candidate) => candidate.id === item.id))] : page); setMore(page.length === 10); setLoaded(true); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  async function registration() { setBusy(true); setError(''); try { setContext(await request<RegistrationContext>(`${base}/registration-context`)); } catch (cause) { setContext(null); setError(messageOf(cause)); } finally { setBusy(false); } }
  async function register(body: object, family: string) { setBusy(true); setError(''); try { const hash = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(family.trim())); const input = { ...body, split_family_sha256: Array.from(new Uint8Array(hash), (byte) => byte.toString(16).padStart(2, '0')).join('') }; const key = JSON.stringify(input); if (pending.current?.key !== key) pending.current = { key, id: crypto.randomUUID().replaceAll('-', '') }; const value = await post<ComparisonCapture>(base, { ...input, request_id: pending.current.id }); pending.current = null; setContext(null); setItems((old) => [{ id: value.id, title: value.protocol.title }, ...old.filter((item) => item.id !== value.id)]); setLoaded(true); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  return <Detail title="Protokole bağlı özel karşılaştırmalar"><p>Tek geçiş ve koşullu yapısal düzeltme için aynı özel girdiyi karşılaştırın. Mevcut taslak korunur; sonuçlar kendi kaynakları ve ölçütleriyle ayrı değerlendirilir.</p><div className="practice-record-actions"><button className="text-button" disabled={busy} onClick={() => void registration()}>Yeni deneme protokolünü hazırla</button><button className="text-button" disabled={busy} onClick={() => void history()}>Deneme kayıtlarını getir</button></div>{context && <RegistrationForm key={context.context_sha256} context={context} busy={busy} onSave={(body, family) => void register(body, family)} />}{items.map((item) => <ComparisonCard key={item.id} {...item} base={base} suggestionBase={suggestionBase} onSource={onSource} />)}{loaded && !items.length && <p>Bu analiz için kayıtlı deneme yok.</p>}{more && <button className="text-button" disabled={busy} onClick={() => void history(true)}>Önceki denemeleri getir</button>}{error && <Notice error>{error}</Notice>}</Detail>;
}
