import { useEffect, useState, type FormEvent } from 'react';
import { post, request } from '../../api';
import { Detail, Field, Notice } from '../../components';
import type { DocumentRecord, Matter, Passage } from '../../types';
import { FACT_LABELS, locatorText, messageOf } from '../../utils';
import { AnalysisCheckPanel } from './AnalysisView';
import { ANALYSIS_LABELS } from './analysisTypes';
import { analysisForm, type AnalysisContent, type AnalysisForm, type AnalysisRecord, type AnalysisSelection } from './analysisTypes';

type Choice = { id: string; label: string };
function node(prefix: string) { return `${prefix}_${crypto.randomUUID().replaceAll('-', '').slice(0, 12)}`; }
function textLines(value: string) { return value.split('\n').map((line) => line.trim()).filter(Boolean); }
function RefPicker({ title, choices, value, onChange }: { title: string; choices: Choice[]; value: string[]; onChange: (values: string[]) => void }) {
  return <fieldset className="reference-picker"><legend>{title}</legend>{choices.length ? choices.map((item) => <label className="checkbox-label" key={item.id}><input type="checkbox" checked={value.includes(item.id)} onChange={(event) => onChange(event.target.checked ? [...value, item.id] : value.filter((id) => id !== item.id))} /><span>{item.label}</span></label>) : <p className="small muted">Önce ilgili adımları ekleyin.</p>}</fieldset>;
}

function EvidenceSelections({ matter, selections, onChange }: { matter: Matter; selections: AnalysisSelection[]; onChange: (items: AnalysisSelection[]) => void }) {
  const [documentId, setDocumentId] = useState(''); const [passages, setPassages] = useState<(Passage & { document_revision: number })[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => {
    setPassages([]); setError('');
    if (!documentId) return;
    const controller = new AbortController(); setBusy(true);
    request<DocumentRecord>(`/matters/${encodeURIComponent(matter.id)}/documents/${encodeURIComponent(documentId)}`, { signal: controller.signal })
      .then((data) => setPassages((data.passages || []).map((passage) => ({ ...passage, document_revision: data.revision || 0 })))).catch((cause) => { if (cause.name !== 'AbortError') setError(messageOf(cause)); })
      .finally(() => { if (!controller.signal.aborted) setBusy(false); });
    return () => controller.abort();
  }, [documentId, matter.id]);
  return <Detail title={`Özgün dayanakları seçin (${selections.length}/20)`}>
    <p className="small muted">Seçilen pasajları kural ve alternatiflere ayrıca bağlayın. En fazla 20 pasaj, pasaj başına 4.000 ve toplam 20.000 Unicode karakter. Kısmi alıntıların koşul ve istisnalarını özgün belgede inceleyin.</p>
    <Field label="Kaynak belge">{(id) => <select id={id} value={documentId} onChange={(event) => setDocumentId(event.target.value)}><option value="">Belge seçin</option>{matter.documents?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}</Field>
    {error && <Notice error>{error}</Notice>}{busy && <p>Pasajlar yükleniyor…</p>}
    {passages.map((passage) => <div key={passage.id}><label className="checkbox-label"><input type="checkbox" disabled={!passage.text_sha256 || !passage.document_revision || (!selections.some((item) => item.evidence_id === passage.id) && selections.length >= 20)} checked={selections.some((item) => item.evidence_id === passage.id)} onChange={(event) => onChange(event.target.checked ? [...selections, { evidence_id: passage.id, passage_sha256: passage.text_sha256 || '', document_revision: passage.document_revision, start: 0, end: Math.min(Array.from(passage.text).length, 4000) }] : selections.filter((item) => item.evidence_id !== passage.id))} /><span>{locatorText(passage.locator)} · {passage.text.slice(0, 160)}</span></label></div>)}
    {selections.map((selection) => { const passage = passages.find((item) => item.id === selection.evidence_id); return <div key={selection.evidence_id} className="inline-form"><p className="reference-id">{selection.evidence_id}</p><div className="form-grid"><Field label="Başlangıç · dahil">{(id) => <input id={id} type="number" required min={0} value={selection.start} onChange={(event) => onChange(selections.map((item) => item.evidence_id === selection.evidence_id ? { ...item, start: Number(event.target.value) } : item))} />}</Field><Field label="Son konum · dahil değil">{(id) => <input id={id} type="number" required min={selection.start + 1} max={selection.start + 4000} value={selection.end} onChange={(event) => onChange(selections.map((item) => item.evidence_id === selection.evidence_id ? { ...item, end: Number(event.target.value) } : item))} />}</Field></div>{passage?.text_sha256 && (passage.text_sha256 !== selection.passage_sha256 || passage.document_revision !== selection.document_revision) && <><Notice error>Bu pasaj seçildikten sonra değişmiş. Güncel metni inceleyip yeniden bağlayın.</Notice><button type="button" className="text-button" onClick={() => onChange(selections.map((item) => item.evidence_id === selection.evidence_id ? { evidence_id: passage.id, passage_sha256: passage.text_sha256!, document_revision: passage.document_revision, start: 0, end: Math.min(Array.from(passage.text).length, 4000) } : item))}>Güncel pasajı yeniden bağla · alıntı aralığını sıfırlar</button></>}{passage ? <p className="authored-text">{Array.from(passage.text).slice(selection.start, selection.end).join('')}</p> : <p className="small muted">Bu aralığı incelemek için özgün belgeyi yukarıdan seçin.</p>}<button type="button" className="text-button" onClick={() => onChange(selections.filter((item) => item.evidence_id !== selection.evidence_id))}>Dayanak seçimini kaldır</button></div>; })}
  </Detail>;
}

export function AnalysisEditor({ matter, record, onCancel, onSave }: { matter: Matter; record?: AnalysisRecord; onCancel: () => void; onSave: () => Promise<void> }) {
  const [form, setForm] = useState<AnalysisForm>(() => analysisForm(record, matter.facts)); const [changeNote, setChangeNote] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [preview, setPreview] = useState<AnalysisContent | null>(null);
  const base = `/matters/${encodeURIComponent(matter.id)}/analyses`;
  function update(next: AnalysisForm) { setForm(next); setPreview(null); setError(''); }
  const factChoices = (matter.facts || []).map((fact) => ({ id: fact.id, revision: fact.revision, label: `${FACT_LABELS[fact.status]} · ${fact.text.slice(0, 180)}` }));
  const premiseChoices = form.premises.map((item) => ({ id: item.id, label: `${item.id} · ${item.kind === 'fact' ? factChoices.find((fact) => fact.id === item.fact_id)?.label || 'Olgu seçilmedi' : item.text || ANALYSIS_LABELS[item.kind]}` }));
  const evidenceChoices = form.evidence.map((item) => ({ id: item.evidence_id, label: `${item.evidence_id} [${item.start}, ${item.end})` }));
  const payload = () => ({ ...form, ...(record ? { expected_revision: record.revision, change_note: changeNote } : {}) });
  async function check() { setBusy(true); setError(''); setPreview(null); try { setPreview(await post<AnalysisContent>(`${base}/check`, payload())); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await post(record ? `${base}/${encodeURIComponent(record.id)}/versions` : base, payload()); await onSave(); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  return <form className="inline-form" onSubmit={save} aria-label="Yapılandırılmış analiz düzenleyicisi"><h3>{record ? `Analiz · Yeni sürüm ${record.version + 1}` : 'Yeni analiz taslağı'}</h3>
    <p className="small muted">Tek bir meseleyi inceleyin. Boş veya bilinmeyen adımlar saklanabilir; kontroller bunları görünür kılar. Yeni sürüm, önceki metni ve olgu defterini değiştirmez.</p>
    {record?.freshness.status === 'stale' && <Notice error>Önceki dayanaklar değişmiş. Düzenleyicide görünen güncel olgu kayıtları yeni sürüme bağlanacak; metni ve koşulları bunlara göre yeniden inceleyin. Değişen pasajları ayrıca yeniden seçin.</Notice>}<fieldset disabled={busy} className="analysis-editor-fields">
      <div className="form-grid"><Field label="Analiz başlığı" className="span-full">{(id) => <input id={id} autoFocus required minLength={3} maxLength={200} value={form.title} onChange={(event) => update({ ...form, title: event.target.value })} />}</Field><Field label="Hukuki mesele veya soru" className="span-full">{(id) => <textarea id={id} required minLength={3} maxLength={2000} rows={2} value={form.issue} onChange={(event) => update({ ...form, issue: event.target.value })} />}</Field><Field label="Süreç ve talep">{(id) => <textarea id={id} maxLength={2000} rows={2} value={form.posture} onChange={(event) => update({ ...form, posture: event.target.value })} />}</Field><Field label="Olay tarihi · bilinmiyorsa boş bırakın">{(id) => <input id={id} type="date" value={form.event_date || ''} onChange={(event) => update({ ...form, event_date: event.target.value || null })} />}</Field></div>
      <EvidenceSelections matter={matter} selections={form.evidence} onChange={(evidence) => { const ids = new Set(evidence.map((item) => item.evidence_id)); update({ ...form, evidence, rules: form.rules.map((rule) => ({ ...rule, evidence_ids: rule.evidence_ids.filter((id) => ids.has(id)) })), alternatives: form.alternatives.map((item) => ({ ...item, evidence_ids: item.evidence_ids.filter((id) => ids.has(id)) })) }); }} />
      <h4>1 · Öncüller ({form.premises.length}/20)</h4>
      {form.premises.map((premise) => <div className="inline-form" key={premise.id}><p className="small-label">{premise.id}</p><Field label="Öncül türü">{(id) => <select id={id} value={premise.kind} onChange={(event) => update({ ...form, premises: form.premises.map((item) => item.id === premise.id ? { ...item, kind: event.target.value as typeof premise.kind, fact_id: null, fact_revision: null, text: '' } : item) })}>{['fact', 'assumption', 'unknown'].map((kind) => <option key={kind} value={kind}>{ANALYSIS_LABELS[kind]}</option>)}</select>}</Field>{premise.kind === 'fact' ? <Field label="Olgu defterindeki kayıt">{(id) => <select id={id} required value={premise.fact_id || ''} onChange={(event) => update({ ...form, premises: form.premises.map((item) => item.id === premise.id ? { ...item, fact_id: event.target.value, fact_revision: factChoices.find((fact) => fact.id === event.target.value)?.revision ?? null } : item) })}><option value="">Olgu seçin</option>{factChoices.map((fact) => <option key={fact.id} value={fact.id}>{fact.label}</option>)}</select>}</Field> : <Field label={premise.kind === 'assumption' ? 'Açık varsayım' : 'Bilinmeyen bilgi veya soru'}>{(id) => <textarea id={id} required maxLength={4000} rows={2} value={premise.text} onChange={(event) => update({ ...form, premises: form.premises.map((item) => item.id === premise.id ? { ...item, text: event.target.value } : item) })} />}</Field>}{premise.kind === 'fact' && premise.fact_id && factChoices.find((fact) => fact.id === premise.fact_id)?.revision !== premise.fact_revision && <><Notice error>Seçilen olgu, düzenleyici açıldıktan sonra değişti veya artık erişilebilir değil. Güncel kaydı inceleyin; eski sürümle kayıt yapılamaz.</Notice><button type="button" className="text-button" disabled={!factChoices.some((fact) => fact.id === premise.fact_id)} onClick={() => update({ ...form, premises: form.premises.map((item) => item.id === premise.id ? { ...item, fact_revision: factChoices.find((fact) => fact.id === premise.fact_id)?.revision ?? null } : item) })}>Görünen güncel olgu sürümünü bağla</button></>}<button type="button" className="text-button" onClick={() => update({ ...form, premises: form.premises.filter((item) => item.id !== premise.id), applications: form.applications.map((item) => ({ ...item, premise_ids: item.premise_ids.filter((id) => id !== premise.id), assessments: item.assessments.map((assessment) => ({ ...assessment, premise_ids: assessment.premise_ids.filter((id) => id !== premise.id) })) })) })}>Öncülü ve adım bağlantılarını kaldır</button></div>)}
      <button type="button" className="text-button" disabled={form.premises.length >= 20} onClick={() => update({ ...form, premises: [...form.premises, { id: node('p'), kind: 'fact', fact_id: null, fact_revision: null, text: '' }] })}>Öncül ekle</button>
      <h4>2 · Kural veya sözleşme maddesi adayları ({form.rules.length}/12)</h4>
      {form.rules.map((rule) => <div className="inline-form" key={rule.id}><p className="small-label">{rule.id}</p><Field label="Kuralın niteliği">{(id) => <select id={id} value={rule.kind} onChange={(event) => update({ ...form, rules: form.rules.map((item) => item.id === rule.id ? { ...item, kind: event.target.value as typeof rule.kind } : item) })}><option value="contract_clause">Sözleşme maddesi adayı</option><option value="legal_norm">Mevzuat kuralı adayı · otorite doğrulanmadı</option></select>}</Field><Field label="Avukatın kural yorumu">{(id) => <textarea id={id} required maxLength={4000} rows={3} value={rule.text} onChange={(event) => update({ ...form, rules: form.rules.map((item) => item.id === rule.id ? { ...item, text: event.target.value } : item) })} />}</Field><RefPicker title="Kuralın özgün dayanakları" choices={evidenceChoices} value={rule.evidence_ids} onChange={(evidence_ids) => update({ ...form, rules: form.rules.map((item) => item.id === rule.id ? { ...item, evidence_ids } : item) })} />
        {rule.conditions.map((condition) => <div key={condition.id}><p className="small muted">{condition.id}</p><Field label="Koşul veya istisna">{(id) => <input id={id} required maxLength={4000} value={condition.text} onChange={(event) => update({ ...form, rules: form.rules.map((item) => item.id === rule.id ? { ...item, conditions: item.conditions.map((entry) => entry.id === condition.id ? { ...entry, text: event.target.value } : entry) } : item) })} />}</Field><div className="form-grid"><Field label="Koşul türü">{(id) => <select id={id} value={condition.kind} onChange={(event) => update({ ...form, rules: form.rules.map((item) => item.id === rule.id ? { ...item, conditions: item.conditions.map((entry) => entry.id === condition.id ? { ...entry, kind: event.target.value as typeof condition.kind } : entry) } : item) })}>{['element', 'exception', 'jurisdiction', 'burden'].map((kind) => <option value={kind} key={kind}>{ANALYSIS_LABELS[kind]}</option>)}</select>}</Field><Field label="Bu önerme için gereken durum">{(id) => <select id={id} value={condition.required_status} onChange={(event) => update({ ...form, rules: form.rules.map((item) => item.id === rule.id ? { ...item, conditions: item.conditions.map((entry) => entry.id === condition.id ? { ...entry, required_status: event.target.value as typeof condition.required_status } : entry) } : item) })}><option value="met">Karşılanması gerekir</option><option value="not_met">Karşılanmaması gerekir</option></select>}</Field></div><button type="button" className="text-button" onClick={() => update({ ...form, rules: form.rules.map((item) => item.id === rule.id ? { ...item, conditions: item.conditions.filter((entry) => entry.id !== condition.id) } : item), applications: form.applications.map((item) => ({ ...item, assessments: item.assessments.filter((entry) => entry.condition_id !== condition.id) })) })}>Koşulu ve değerlendirmesini kaldır</button></div>)}
        <button type="button" className="text-button" disabled={rule.conditions.length >= 12} onClick={() => { const condition = { id: node('c'), text: '', kind: 'element' as const, required_status: 'met' as const }; update({ ...form, rules: form.rules.map((item) => item.id === rule.id ? { ...item, conditions: [...item.conditions, condition] } : item), applications: form.applications.map((item) => item.rule_id === rule.id ? { ...item, assessments: [...item.assessments, { condition_id: condition.id, status: 'unknown', premise_ids: [] }] } : item) }); }}>Koşul / istisna ekle</button><button type="button" className="text-button" onClick={() => { const removed = new Set(form.applications.filter((item) => item.rule_id === rule.id).map((item) => item.id)); update({ ...form, rules: form.rules.filter((item) => item.id !== rule.id), applications: form.applications.filter((item) => !removed.has(item.id)), conclusion: { ...form.conclusion, application_ids: form.conclusion.application_ids.filter((id) => !removed.has(id)) } }); }}>Kuralı ve bağlı uygulamaları kaldır</button>
      </div>)}
      <button type="button" className="text-button" disabled={form.rules.length >= 12} onClick={() => update({ ...form, rules: [...form.rules, { id: node('r'), kind: 'contract_clause', text: '', evidence_ids: [], conditions: [] }] })}>Kural adayı ekle</button>
      <h4>3 · Uygulama adımları ({form.applications.length}/12)</h4><p className="small muted">Eksik koşul değerlendirmeleri düzenleyicide bilinmeyen olarak açılır. Hangi öncüllere dayanarak değişiklik yaptığınızı açıkça belirtin.</p>
      {form.applications.map((app) => <div className="inline-form" key={app.id}><p className="small-label">{app.id}</p><Field label="Uygulanacak kural">{(id) => <select id={id} required value={app.rule_id} onChange={(event) => { const rule = form.rules.find((item) => item.id === event.target.value); update({ ...form, applications: form.applications.map((item) => item.id === app.id ? { ...item, rule_id: event.target.value, assessments: (rule?.conditions || []).map((condition) => ({ condition_id: condition.id, status: 'unknown', premise_ids: [] })) } : item) }); }}><option value="">Kural seçin</option>{form.rules.map((rule) => <option key={rule.id} value={rule.id}>{rule.id} · {rule.text.slice(0, 100)}</option>)}</select>}</Field><RefPicker title="Uygulamanın öncülleri" choices={premiseChoices} value={app.premise_ids} onChange={(premise_ids) => update({ ...form, applications: form.applications.map((item) => item.id === app.id ? { ...item, premise_ids, assessments: item.assessments.map((assessment) => ({ ...assessment, premise_ids: assessment.premise_ids.filter((id) => premise_ids.includes(id)) })) } : item) })} /><Field label="Öncülün kuralla ilişkisi ve ayrımlar">{(id) => <textarea id={id} required maxLength={4000} rows={3} value={app.rationale} onChange={(event) => update({ ...form, applications: form.applications.map((item) => item.id === app.id ? { ...item, rationale: event.target.value } : item) })} />}</Field>
        {app.assessments.map((assessment) => <div key={assessment.condition_id}><Field label={`Koşul: ${form.rules.find((rule) => rule.id === app.rule_id)?.conditions.find((condition) => condition.id === assessment.condition_id)?.text || assessment.condition_id}`}>{(id) => <select id={id} value={assessment.status} onChange={(event) => update({ ...form, applications: form.applications.map((item) => item.id === app.id ? { ...item, assessments: item.assessments.map((entry) => entry.condition_id === assessment.condition_id ? { ...entry, status: event.target.value as typeof assessment.status } : entry) } : item) })}>{['unknown', 'met', 'not_met'].map((status) => <option key={status} value={status}>{ANALYSIS_LABELS[status]}</option>)}</select>}</Field><RefPicker title="Bu koşul değerlendirmesinin öncülleri" choices={premiseChoices.filter((item) => app.premise_ids.includes(item.id))} value={assessment.premise_ids} onChange={(premise_ids) => update({ ...form, applications: form.applications.map((item) => item.id === app.id ? { ...item, assessments: item.assessments.map((entry) => entry.condition_id === assessment.condition_id ? { ...entry, premise_ids } : entry) } : item) })} /></div>)}
        <button type="button" className="text-button" onClick={() => update({ ...form, applications: form.applications.filter((item) => item.id !== app.id), conclusion: { ...form.conclusion, application_ids: form.conclusion.application_ids.filter((id) => id !== app.id) } })}>Uygulamayı ve sonuç bağlantısını kaldır</button>
      </div>)}
      <button type="button" className="text-button" disabled={form.applications.length >= 12 || !form.rules.length} onClick={() => update({ ...form, applications: [...form.applications, { id: node('a'), rule_id: '', premise_ids: [], rationale: '', assessments: [] }] })}>Uygulama ekle</button>
      <h4>4 · Alternatifler ve karşı argümanlar ({form.alternatives.length}/12)</h4>
      {form.alternatives.map((alternative) => <div className="inline-form" key={alternative.id}><p className="small-label">{alternative.id}</p><Field label="Alternatif türü">{(id) => <select id={id} value={alternative.kind} onChange={(event) => update({ ...form, alternatives: form.alternatives.map((item) => item.id === alternative.id ? { ...item, kind: event.target.value as typeof alternative.kind } : item) })}>{['adverse_argument', 'alternative_classification', 'material_distinction', 'search_gap'].map((kind) => <option key={kind} value={kind}>{ANALYSIS_LABELS[kind]}</option>)}</select>}</Field><Field label="Karşı argüman, ayrım veya eksik araştırma">{(id) => <textarea id={id} required maxLength={4000} rows={3} value={alternative.text} onChange={(event) => update({ ...form, alternatives: form.alternatives.map((item) => item.id === alternative.id ? { ...item, text: event.target.value } : item) })} />}</Field><RefPicker title="Alternatifin özgün dayanakları" choices={evidenceChoices} value={alternative.evidence_ids} onChange={(evidence_ids) => update({ ...form, alternatives: form.alternatives.map((item) => item.id === alternative.id ? { ...item, evidence_ids } : item) })} /><button type="button" className="text-button" onClick={() => update({ ...form, alternatives: form.alternatives.filter((item) => item.id !== alternative.id), conclusion: { ...form.conclusion, alternative_ids: form.conclusion.alternative_ids.filter((id) => id !== alternative.id) } })}>Alternatifi ve sonuç bağlantısını kaldır</button></div>)}
      <button type="button" className="text-button" disabled={form.alternatives.length >= 12} onClick={() => update({ ...form, alternatives: [...form.alternatives, { id: node('alt'), kind: 'search_gap', text: '', evidence_ids: [] }] })}>Alternatif / araştırma boşluğu ekle</button>
      <h4>5 · Geçici sonuç ve sonraki adım</h4><RefPicker title="Sonucun bağlı uygulamaları" choices={form.applications.map((item) => ({ id: item.id, label: `${item.id} · ${item.rationale.slice(0, 120)}` }))} value={form.conclusion.application_ids} onChange={(application_ids) => update({ ...form, conclusion: { ...form.conclusion, application_ids } })} /><RefPicker title="Sonucun bağlı alternatifleri" choices={form.alternatives.map((item) => ({ id: item.id, label: `${item.id} · ${item.text.slice(0, 120)}` }))} value={form.conclusion.alternative_ids} onChange={(alternative_ids) => update({ ...form, conclusion: { ...form.conclusion, alternative_ids } })} />
      <Field label="Avukatın geçici sonuç metni">{(id) => <textarea id={id} required maxLength={4000} rows={4} value={form.conclusion.text} onChange={(event) => update({ ...form, conclusion: { ...form.conclusion, text: event.target.value } })} />}</Field><Field label="Talep edilen sonuç değerlendirmesi">{(id) => <select id={id} value={form.conclusion.requested_disposition} onChange={(event) => update({ ...form, conclusion: { ...form.conclusion, requested_disposition: event.target.value as typeof form.conclusion.requested_disposition } })}>{['conditional', 'withheld', 'supported_candidate'].map((value) => <option key={value} value={value}>{ANALYSIS_LABELS[value]}</option>)}</select>}</Field><Field label="Belirsizlikler · her satıra bir madde">{(id) => <textarea id={id} maxLength={80000} rows={3} value={form.conclusion.uncertainty.join('\n')} onChange={(event) => { setPreview(null); setForm({ ...form, conclusion: { ...form.conclusion, uncertainty: event.target.value.split('\n') } }); }} onBlur={() => update({ ...form, conclusion: { ...form.conclusion, uncertainty: textLines(form.conclusion.uncertainty.join('\n')) } })} />}</Field><Field label="Sonraki inceleme veya delil adımı">{(id) => <textarea id={id} required maxLength={4000} rows={2} value={form.conclusion.next_step} onChange={(event) => update({ ...form, conclusion: { ...form.conclusion, next_step: event.target.value } })} />}</Field>
      {record && <Field label="Bu sürümde ne değişti?">{(id) => <textarea id={id} required minLength={3} maxLength={2000} rows={2} value={changeNote} onChange={(event) => { setChangeNote(event.target.value); setPreview(null); }} />}</Field>}
      <div className="form-actions"><button type="button" className="button secondary" onClick={onCancel}>Vazgeç</button><button type="button" className="button secondary" onClick={() => void check()}>Yapıyı kontrol et</button><button className="button primary">{record ? 'Yeni analiz sürümünü kaydet' : 'Analiz taslağını kaydet'}</button></div>
    </fieldset>
    {busy && <p>Kontroller ve dayanaklar doğrulanıyor…</p>}{error && <Notice error>{error}</Notice>}
    {preview && <div className="inline-form"><p className="small muted">Kontrol önizlemesi · Henüz saklanmadı. Kaydetme sırasında kontroller yeniden çalışır.</p><AnalysisCheckPanel checks={preview.checks} /></div>}
  </form>;
}
