import { useRef, useState } from 'react';
import { post, request } from '../../api';
import { Badge, Detail, Field, Notice } from '../../components';
import { formatDate, locatorText, messageOf } from '../../utils';
import type { AnalysisRecord, AnalysisReviewContext, AnalysisReviewEvent, AnalysisReviewFinding, AnalysisReviewProjection, ReviewCriterionKey, ReviewOutcome } from './analysisTypes';

export const REVIEW_LABELS: Record<ReviewCriterionKey, string> = { sources: 'Özgün kaynaklar', reasoning: 'Gerekçe ve koşullar', fact_roles: 'Olgu rolleri ve çelişkiler', limits: 'Alternatifler ve kapsam sınırları', ai_contribution: 'Model katkısı' };
const OUTCOME_LABELS: Record<ReviewOutcome, string> = { confirmed: 'Değerlendirdim', needs_change: 'Değişiklik gerekli', not_applicable: 'Bu sürümde model katkısı yok' };

export function ReviewEventDetails({ event, onSource }: { event: AnalysisReviewEvent; onSource: (id: string) => void }) {
  return <Detail title={`İnceleme #${event.sequence} · ${formatDate(event.created_at, true)}`}>
    <p>{event.decision === 'reviewed_conditional' ? 'Koşullu özel taslak incelemesi kaydedildi.' : 'Avukat değişiklik istedi.'} {event.reviewer_name}</p><p className="authored-text">{event.note}</p>
    <p className="small muted">Avukatın beyanıdır; kaynak yorumunu otomatik doğrulamaz. Kamu/historik otorite incelemesi veya makine hukuki onayı değildir.</p>
    <ul>{event.criteria.map((item) => <li key={item.criterion}><strong>{REVIEW_LABELS[item.criterion]}:</strong> {OUTCOME_LABELS[item.outcome]}{item.note && ` · ${item.note}`}</li>)}</ul>
    {event.findings.map((item, index) => <div key={index}><p className="authored-text"><strong>{item.target_id} · {item.severity === 'critical' ? 'Kritik' : item.severity === 'major' ? 'Esaslı' : 'Not'}:</strong> {item.text}</p>{item.suggested_change && <p>Önerilen değişiklik: {item.suggested_change}</p>}{item.evidence_ids.map((id) => <button key={id} className="source-link" onClick={() => onSource(id)}>Bulgunun özgün dayanağı</button>)}</div>)}
    <Detail title="İnceleme sürümü ve kayıt bağı"><p className="reference-id">Sürüm: {event.version_id} · İnceleyen: {event.reviewer_id}</p><p className="reference-id">İçerik SHA-256: {event.content_sha256} · Ölçütler: {event.recipe}</p></Detail>
  </Detail>;
}

export function ReviewSummary({ review, onSource }: { review?: AnalysisReviewProjection; onSource: (id: string) => void }) {
  if (!review?.latest) return null;
  return <div><Badge status={review.effective_state === 'reviewed_conditional' ? 'reviewed' : review.effective_state === 'stale' ? 'stale' : undefined}>{review.effective_state === 'reviewed_conditional' ? 'Avukat inceledi · Koşullu özel taslak' : review.effective_state === 'stale' ? 'Önceki avukat incelemesi güncel değil' : 'Avukat değişiklik istedi'}</Badge>
    {review.reasons.length > 0 && <Notice error>{review.reasons.map((reason) => <p key={reason}>{reason}</p>)}Önceki karar korunur; güncel çalışma için yeniden inceleme gereklidir.</Notice>}
    <ReviewEventDetails event={review.latest} onSource={onSource} />
  </div>;
}

export function ReviewHistory({ matterId, analysisId, versionId, onSource }: { matterId: string; analysisId: string; versionId: string; onSource: (id: string) => void }) {
  const [events, setEvents] = useState<AnalysisReviewEvent[]>([]); const [loaded, setLoaded] = useState(false); const [more, setMore] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function load(append = false) { setBusy(true); setError(''); try { const page = await request<AnalysisReviewEvent[]>(`/matters/${encodeURIComponent(matterId)}/analyses/${encodeURIComponent(analysisId)}/reviews?version_id=${encodeURIComponent(versionId)}&limit=10&offset=${append ? events.length : 0}`); setEvents((old) => append ? [...old, ...page.filter((item) => !old.some((event) => event.id === item.id))] : page); setLoaded(true); setMore(page.length === 10); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  return <Detail title="Bu sürümün inceleme kararları"><p className="small muted">Kararlar metni değiştirmez. Son karar geçerli görünümü belirler; önceki kararlar ve bulgular korunur.</p><button className="text-button" disabled={busy} onClick={() => void load()}>{loaded ? 'İncelemeleri yenile' : 'İncelemeleri getir'}</button>{events.map((event) => <ReviewEventDetails key={event.id} event={event} onSource={onSource} />)}{loaded && !events.length && <p className="small muted">Bu sürüm için kaydedilmiş avukat incelemesi yok.</p>}{more && <button className="text-button" disabled={busy} onClick={() => void load(true)}>Önceki incelemeleri getir</button>}{error && <Notice error>{error}</Notice>}</Detail>;
}

type EditableFinding = AnalysisReviewFinding & { localId: string };
type ReviewSubmission = { decision: AnalysisReviewEvent['decision']; note: string; criteria: { criterion: ReviewCriterionKey; outcome: ReviewOutcome; note: string }[]; findings: AnalysisReviewFinding[] };
export function AnalysisReviewForm({ context, onSource, onSubmit, busy }: { context: AnalysisReviewContext; onSource: (id: string) => void; onSubmit: (body: ReviewSubmission) => Promise<void>; busy: boolean }) {
  const [decision, setDecision] = useState<AnalysisReviewEvent['decision']>('changes_requested'); const [note, setNote] = useState('');
  const [outcomes, setOutcomes] = useState<Partial<Record<ReviewCriterionKey, ReviewOutcome>>>({}); const [notes, setNotes] = useState<Partial<Record<ReviewCriterionKey, string>>>({}); const [findings, setFindings] = useState<EditableFinding[]>([]);
  const criteria = (Object.keys(context.criteria) as ReviewCriterionKey[]).filter((key) => outcomes[key]).map((key) => ({ criterion: key, outcome: outcomes[key]!, note: notes[key] || '' }));
  const acceptable = context.can_accept && criteria.length === 5 && criteria.every((item) => item.outcome !== 'needs_change') && findings.every((item) => item.severity === 'note');
  const explained = criteria.every((item) => item.outcome === 'confirmed' || item.note.trim().length >= 3);
  const validFindings = findings.every((item) => item.text.trim().length >= 3);
  const hasChange = findings.length > 0 || criteria.some((item) => item.outcome === 'needs_change');
  function updateFinding(localId: string, change: Partial<EditableFinding>) { setFindings((old) => old.map((item) => item.localId === localId ? { ...item, ...change } : item)); }
  return <form onSubmit={(event) => { event.preventDefault(); void onSubmit({ decision, note, criteria, findings: findings.map(({ localId: _localId, ...item }) => item) }); }}>
    <p>Bu karar, gösterilen sürümün koşullu özel taslağıyla sınırlıdır. Kamu mevzuatı, geçmiş sürüm, yetki veya karşı içtihat doğruluğunu onaylamaz. Tüm metin, kaynak seçimi ve belirsizlikleri değerlendirin.</p>
    {(!context.can_accept || !context.current_version) && <Notice error>{!context.current_version ? 'Gösterilen sürüm güncel sürüm değil; karar kaydedilemez.' : context.freshness.status === 'stale' ? 'Özel dayanaklar değişti; yalnız değişiklik isteği kaydedilebilir.' : `${context.critical_count} kritik yapısal kontrol var; yalnız değişiklik isteği kaydedilebilir.`}</Notice>}
    <Detail title={`İncelenecek özgün alıntılar (${context.sources.length})`}><p className="small muted">Karar bütün seçime bağlanır; kaynak düğmesine basmak inceleme yaptığınızı kanıtlamaz. Saklanan metni özgün belgenin bağlamıyla karşılaştırın.</p>{context.sources.map((source) => <p key={source.evidence_id}><button type="button" className="source-link" onClick={() => onSource(source.evidence_id)}>{source.name} · {locatorText(source.locator)} · [{source.start}, {source.end})</button><span className="reference-id">Alıntı SHA-256: {source.quote_sha256}</span></p>)}</Detail>
    <Field label="İnceleme kararı">{(id) => <select id={id} disabled={busy || !context.can_record} value={decision} onChange={(event) => setDecision(event.target.value as typeof decision)}><option value="changes_requested">Değişiklik gerekli</option><option value="reviewed_conditional" disabled={!context.can_accept}>Koşullu özel taslak incelendi</option></select>}</Field>
    {(Object.entries(context.criteria) as [ReviewCriterionKey, string][]).map(([key, description]) => <div key={key}><Field label={REVIEW_LABELS[key]} hint={description}>{(id) => <select id={id} disabled={busy || !context.can_record} value={outcomes[key] || ''} onChange={(event) => setOutcomes((old) => ({ ...old, [key]: event.target.value as ReviewOutcome }))}><option value="">Değerlendirme seçin</option><option value="confirmed">Değerlendirdim</option><option value="needs_change">Değişiklik gerekli</option>{key === 'ai_contribution' && !context.ai_contribution_required && <option value="not_applicable">Bu sürümde model katkısı yok</option>}</select>}</Field><Detail title={`${REVIEW_LABELS[key]} — ölçüt notu`} open={outcomes[key] === 'needs_change' || outcomes[key] === 'not_applicable' ? true : undefined}><Field label={`${REVIEW_LABELS[key]} notu`} hint="Değişiklik gerekli veya uygulanamaz değerlendirmesinde en az 3 karakter açıklayın.">{(id) => <textarea id={id} rows={2} maxLength={1000} disabled={busy} value={notes[key] || ''} onChange={(event) => setNotes((old) => ({ ...old, [key]: event.target.value }))} />}</Field></Detail></div>)}
    <Detail title={`İnceleme bulguları (${findings.length})`}>{findings.map((item) => <div className="practice-record" key={item.localId}><Field label="Bulgunun adımı">{(id) => <select id={id} disabled={busy} value={item.target_id} onChange={(event) => updateFinding(item.localId, { target_id: event.target.value })}>{context.targets.map((target) => <option key={target} value={target}>{target}</option>)}</select>}</Field><Field label="Bulgunun önemi">{(id) => <select id={id} disabled={busy} value={item.severity} onChange={(event) => updateFinding(item.localId, { severity: event.target.value as typeof item.severity })}><option value="critical">Kritik · Sonuç düzeltilmeli</option><option value="major">Esaslı · Düzeltme gerekli</option><option value="note">Not · Koşullu sınırlama</option></select>}</Field><Field label="Bulgu">{(id) => <textarea id={id} rows={3} maxLength={2000} disabled={busy} value={item.text} onChange={(event) => updateFinding(item.localId, { text: event.target.value })} />}</Field><Field label="Önerilen değişiklik (isteğe bağlı)">{(id) => <textarea id={id} rows={2} maxLength={2000} disabled={busy} value={item.suggested_change} onChange={(event) => updateFinding(item.localId, { suggested_change: event.target.value })} />}</Field><fieldset disabled={busy}><legend>Bulgunun özgün dayanakları (isteğe bağlı)</legend>{context.sources.map((source) => <label key={source.evidence_id}><input type="checkbox" checked={item.evidence_ids.includes(source.evidence_id)} onChange={(event) => updateFinding(item.localId, { evidence_ids: event.target.checked ? [...item.evidence_ids, source.evidence_id] : item.evidence_ids.filter((id) => id !== source.evidence_id) })} />{source.name} · [{source.start}, {source.end})</label>)}</fieldset><button type="button" className="text-button" disabled={busy} onClick={() => setFindings((old) => old.filter((finding) => finding.localId !== item.localId))}>Bulgu satırını kaldır</button></div>)}<button type="button" className="text-button" disabled={busy || findings.length >= 20 || !context.can_record} onClick={() => setFindings((old) => [...old, { localId: crypto.randomUUID(), target_id: 'conclusion', severity: 'major', text: '', suggested_change: '', evidence_ids: [] }])}>Bulgu ekle</button></Detail>
    <Field label="İnceleme kararının gerekçesi">{(id) => <textarea id={id} rows={3} minLength={3} maxLength={2000} disabled={busy} value={note} onChange={(event) => setNote(event.target.value)} />}</Field>
    <button className="button secondary" type="submit" disabled={busy || !context.can_record || note.trim().length < 3 || !criteria.length || !explained || !validFindings || (decision === 'reviewed_conditional' ? !acceptable : !hasChange)}>{busy ? 'Kaydediliyor…' : 'İnceleme kararını kaydet'}</button><p className="small muted">Metin ve önceki kararlar korunur. Kritik/esaslı bulgu, değerlendirilmemiş ölçüt veya değişmiş dayanak varken incelendi durumuna geçilemez. Yeni metin sürümü yeniden inceleme gerektirir.</p>
  </form>;
}

export function AnalysisReviews({ matterId, record, onSource, onSaved }: { matterId: string; record: AnalysisRecord; onSource: (id: string) => void; onSaved: () => Promise<void> }) {
  const [context, setContext] = useState<AnalysisReviewContext | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const pending = useRef<{ key: string; id: string } | null>(null);
  const base = `/matters/${encodeURIComponent(matterId)}/analyses/${encodeURIComponent(record.id)}/reviews`;
  async function load() { setBusy(true); setError(''); try { setContext(await request<AnalysisReviewContext>(`${base}/context?version_id=${encodeURIComponent(record.latest_version_id)}`)); } catch (cause) { setContext(null); setError(messageOf(cause)); } finally { setBusy(false); } }
  async function save(input: ReviewSubmission) { if (!context) return; setBusy(true); setError(''); const payload = { ...input, version_id: context.version_id, expected_revision: context.expected_revision, content_sha256: context.content_sha256, expected_review_id: context.expected_review_id }; const key = JSON.stringify(payload); if (pending.current?.key !== key) pending.current = { key, id: crypto.randomUUID().replaceAll('-', '') }; try { await post(base, { ...payload, request_id: pending.current.id }); pending.current = null; await onSaved(); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  return <Detail title="Avukat inceleme kararı kaydet"><p>İnceleme, bu sürümün metni, kaynak seçimi ve önceki kararına bağlanır. Model veya yapısal kontrol bir avukat incelemesi yapmış sayılmaz.</p><button className="text-button" disabled={busy} onClick={() => void load()}>{context ? 'İnceleme bağını yenile' : 'Gösterilen sürümün inceleme formunu aç'}</button>{context && <AnalysisReviewForm key={`${context.version_id}:${context.expected_review_id}:${context.recipe}`} context={context} onSource={onSource} onSubmit={save} busy={busy} />}{error && <Notice error>{error}</Notice>}</Detail>;
}
