import { Detail, Field, Notice } from '../../components';
import { FACT_LABELS, locatorText } from '../../utils';
import { ANALYSIS_LABELS, type ComparisonValue, type FindingDisposition, type LinkedObservation, type RevisionAssessment, type RevisionComparison, type SemanticDimension, type SemanticObservation } from './analysisTypes';

export const SEMANTIC_LABELS: Record<SemanticDimension, string> = { entailment: 'Pasajın anlamı ve çıkarım', fact_roles: 'Olgu rolleri ve olumsuzluk', conditions: 'Koşullar ve istisnalar', chronology: 'Zaman ve miktar sınırları', counterevidence: 'Özel belgelerde karşı dayanak', certainty: 'Sonucun gücü ve belirsizlik' };
const OUTCOMES = { confirmed: 'Dayanakla değerlendirdim', needs_change: 'Değişiklik gerekli', not_assessed: 'Değerlendirilmedi', repaired: 'Giderildi · Avukat beyanı', withheld: 'Sonuç bekletildi', unresolved: 'Çözülmedi' };
type EditableSemantic = Omit<SemanticObservation, 'outcome'> & { outcome: SemanticObservation['outcome'] | '' };
type EditableDisposition = Omit<FindingDisposition, 'outcome'> & { outcome: FindingDisposition['outcome'] | '' };
export interface EditableAssessment { observations: EditableSemantic[]; finding_dispositions: EditableDisposition[]; review_seconds: string }

export function emptyAssessment(comparison: RevisionComparison): EditableAssessment {
  return { observations: (Object.keys(SEMANTIC_LABELS) as SemanticDimension[]).map((dimension) => ({ dimension, outcome: '', note: '', target_ids: ['conclusion'], source_refs: [] })), finding_dispositions: comparison.findings.map((item) => ({ finding_index: item.finding_index, outcome: '', note: '', target_ids: [item.target_id], source_refs: [] })), review_seconds: '' };
}

export function assessmentPayload(value: EditableAssessment, comparison: RevisionComparison): RevisionAssessment | null {
  const observations = [...value.observations, ...value.finding_dispositions];
  const changed = new Set(comparison.changes.filter((item) => item.after !== null).map((item) => item.target_id));
  const currentSource = (item: LinkedObservation) => item.source_refs.some((ref) => ref.startsWith('after:'));
  const repairAssessed = (item: EditableDisposition) => item.target_ids.some((target) => changed.has(target) && (['entailment', 'certainty'] as const).every((dimension) => value.observations.some((observation) => observation.dimension === dimension && observation.outcome === 'confirmed' && observation.target_ids.includes(target))));
  const seconds = value.review_seconds === '' ? null : Number(value.review_seconds);
  if (comparison.freshness.status !== 'current' || observations.some((item) => !item.outcome || item.note.trim().length < 3 || !item.target_ids.length)
    || value.observations.some((item) => item.outcome === 'confirmed' && !currentSource(item))
    || value.finding_dispositions.some((item) => (item.outcome === 'repaired' && (!currentSource(item) || !item.target_ids.some((id) => changed.has(id)) || !repairAssessed(item))) || (item.outcome === 'withheld' && comparison.candidate_disposition !== 'withheld'))
    || (seconds !== null && (!Number.isInteger(seconds) || seconds < 1 || seconds > 28800))) return null;
  return { comparison_sha256: comparison.comparison_sha256, observations: value.observations as SemanticObservation[], finding_dispositions: value.finding_dispositions as FindingDisposition[], review_seconds: seconds };
}

export function permitsPositiveReview(value: EditableAssessment, comparison: RevisionComparison): boolean {
  return !value.observations.some((item) => item.outcome === 'needs_change') && !value.finding_dispositions.some((item) => item.outcome === 'unresolved' && comparison.findings.find((finding) => finding.finding_index === item.finding_index)?.severity !== 'note');
}

const NODE_LABELS: Record<string, string> = { id: 'Adım', title: 'Başlık', issue: 'Mesele', posture: 'Süreç', event_date: 'Olay tarihi', text: 'Metin', rationale: 'Gerekçe', kind: 'Tür', status: 'Durum', revision: 'Sürüm', fact_snapshot: 'Olgu kaydı', fact_id: 'Olgu bağı', fact_revision: 'Olgu sürümü', evidence_id: 'Dayanak', evidence_ids: 'Dayanaklar', rule_id: 'Kural bağı', premise_ids: 'Öncüller', application_ids: 'Uygulamalar', alternative_ids: 'Alternatifler', conditions: 'Koşullar', condition_id: 'Koşul bağı', assessments: 'Değerlendirmeler', required_status: 'Gereken durum', requested_disposition: 'İstenen sonuç durumu', uncertainty: 'Belirsizlikler', next_step: 'Sonraki adım' };
function NodeValue({ value, field }: { value: ComparisonValue; field?: string }) {
  if (value === null) return <p className="small muted">Bu sürümde yok.</p>;
  if (Array.isArray(value)) return <ul>{value.map((item, index) => <li key={index}><NodeValue value={item} /></li>)}</ul>;
  if (typeof value === 'object') return <dl>{Object.entries(value).map(([key, item]) => <div key={key}><dt><strong>{NODE_LABELS[key] || key}</strong></dt><dd><NodeValue value={item} field={key} /></dd></div>)}</dl>;
  const label = typeof value === 'string' && ['kind', 'status', 'required_status', 'requested_disposition'].includes(field || '') ? ANALYSIS_LABELS[value] || FACT_LABELS[value as keyof typeof FACT_LABELS] || value : String(value);
  return <span className="authored-text">{label}</span>;
}

export function RevisionComparisonDetails({ comparison, onSource }: { comparison: RevisionComparison; onSource: (id: string) => void }) {
  return <>
    <p>Önceki sürüm {comparison.base_version} → {comparison.candidate_kind ? 'kaydedilmemiş model adayı' : `gösterilen sürüm ${comparison.candidate_version}`}: {comparison.changes.length} değişen adım, {comparison.findings.length} önceki bulgu. Kaynak bağlı değerlendirme avukat beyanıdır.</p>
    <p className="small muted">Özel belge karşı dayanağı, karşı içtihat araştırması değildir. Bir adımın kaldırılması veya kontrolün susması kusurun giderildiğini kanıtlamaz. Zaman kazanımı ve model faydası ölçülmedi.</p>
    {comparison.freshness.status === 'stale' && <Notice error>{comparison.freshness.reasons.join(' ')} Yeni karşılaştırma değerlendirmesi kaydedilemez.</Notice>}
    <Detail title={`Değişen adımları karşılaştır (${comparison.changes.length})`}>{comparison.changes.map((item) => <Detail key={item.target_id} title={item.target_id}><h4>Önceki sürüm {comparison.base_version}</h4><NodeValue value={item.before} /><h4>{comparison.candidate_kind ? 'Kaydedilmemiş model adayı' : `Gösterilen sürüm ${comparison.candidate_version}`}</h4><NodeValue value={item.after} /></Detail>)}{!comparison.changes.length && <p>Metin adımlarında değişiklik yok. Giderildi beyanı kaydedilemez.</p>}</Detail>
    <Detail title={`${comparison.candidate_kind ? 'Taslak ve model adayının' : 'Her iki sürümün'} saklanan alıntıları (${comparison.sources.length})`}><p className="small muted">Saklanan alıntıyı belgenin bağlamıyla karşılaştırın; düğme güncel belgeyi açar.</p>{comparison.sources.map((source) => <div key={source.source_ref}><p><strong>{source.source_ref.startsWith('before:') ? 'Önceki sürüm' : comparison.candidate_kind ? 'Model adayı' : 'Gösterilen sürüm'}</strong> · {source.name} · {locatorText(source.locator)} · [{source.start}, {source.end})</p><p className="authored-text">{source.text}</p><button type="button" className="source-link" onClick={() => onSource(source.evidence_id)}>Özgün belgenin bağlamını aç</button><p className="reference-id">Alıntı SHA-256: {source.quote_sha256}</p></div>)}</Detail>
    <Detail title="Karşılaştırmanın kayıt bağı"><p className="reference-id">Önceki sürüm: {comparison.base_version_id} · içerik: {comparison.base_content_sha256}</p><p className="reference-id">{comparison.candidate_kind ? 'Model adayı' : 'Gösterilen sürüm'}: {comparison.candidate_version_id} · içerik: {comparison.candidate_content_sha256}</p><p className="reference-id">Önceki inceleme: {comparison.base_review_id || 'Yok'} · karşılaştırma: {comparison.comparison_sha256}</p></Detail>
  </>;
}

function ReferencePicker({ value, onChange, comparison, busy }: { value: LinkedObservation; onChange: (change: Partial<LinkedObservation>) => void; comparison: RevisionComparison; busy: boolean }) {
  return <Detail title="Gözlemin adım ve alıntı bağları"><fieldset disabled={busy}><legend>İncelenen adımlar</legend>{comparison.targets.map((id) => <label key={id}><input type="checkbox" checked={value.target_ids.includes(id)} onChange={(event) => onChange({ target_ids: event.target.checked ? [...value.target_ids, id] : value.target_ids.filter((item) => item !== id) })} />{id}</label>)}</fieldset><fieldset disabled={busy}><legend>İncelenen alıntılar</legend>{comparison.sources.map((source) => <label key={source.source_ref}><input type="checkbox" checked={value.source_refs.includes(source.source_ref)} onChange={(event) => onChange({ source_refs: event.target.checked ? [...value.source_refs, source.source_ref] : value.source_refs.filter((item) => item !== source.source_ref) })} />{source.source_ref.startsWith('before:') ? 'Önceki' : comparison.candidate_kind ? 'Model adayı' : 'Gösterilen'} · {source.name} · [{source.start}, {source.end})</label>)}</fieldset></Detail>;
}

export function RevisionAssessmentEditor({ comparison, value, onChange, busy }: { comparison: RevisionComparison; value: EditableAssessment; onChange: (value: EditableAssessment) => void; busy: boolean }) {
  function semantic(index: number, change: Partial<EditableSemantic>) { onChange({ ...value, observations: value.observations.map((item, i) => i === index ? { ...item, ...change } : item) }); }
  function disposition(index: number, change: Partial<EditableDisposition>) { onChange({ ...value, finding_dispositions: value.finding_dispositions.map((item, i) => i === index ? { ...item, ...change } : item) }); }
  return <>
    <p>Altı boyutu ve önceki incelemenin tüm bulgularını ayrı değerlendirin. Olumlu gözlem ve giderildi beyanı, {comparison.candidate_kind ? 'model adayının' : 'gösterilen sürümün'} alıntısına bağlanır. Giderildi beyanı aynı değişen adım için pasajın anlamı ve sonucun gücünün olumlu incelenmesini gerektirir. Değerlendirilmedi seçimi eksikliği görünür tutar.</p>
    {value.observations.map((item, index) => <Detail key={item.dimension} title={SEMANTIC_LABELS[item.dimension]}><Field label={`${SEMANTIC_LABELS[item.dimension]} değerlendirmesi`} hint={comparison.dimensions[item.dimension]}>{(id) => <select id={id} value={item.outcome} disabled={busy} onChange={(event) => semantic(index, { outcome: event.target.value as EditableSemantic['outcome'] })}><option value="">Değerlendirme seçin</option>{(['confirmed', 'needs_change', 'not_assessed'] as const).map((outcome) => <option key={outcome} value={outcome}>{OUTCOMES[outcome]}</option>)}</select>}</Field><Field label={`${SEMANTIC_LABELS[item.dimension]} gerekçesi`}>{(id) => <textarea id={id} rows={2} maxLength={2000} value={item.note} disabled={busy} onChange={(event) => semantic(index, { note: event.target.value })} />}</Field><ReferencePicker value={item} onChange={(change) => semantic(index, change)} comparison={comparison} busy={busy} /></Detail>)}
    {comparison.findings.map((finding, index) => { const item = value.finding_dispositions[index]; return <Detail key={finding.finding_index} title={`Önceki bulgu ${finding.finding_index + 1} · ${finding.target_id}`}><p className="authored-text">{finding.severity === 'critical' ? 'Kritik' : finding.severity === 'major' ? 'Esaslı' : 'Not'} · {finding.text}</p>{finding.suggested_change && <p>İstenen değişiklik: {finding.suggested_change}</p>}<Field label={`Önceki bulgu ${finding.finding_index + 1} durumu`}>{(id) => <select id={id} value={item.outcome} disabled={busy} onChange={(event) => disposition(index, { outcome: event.target.value as EditableDisposition['outcome'] })}><option value="">Değerlendirme seçin</option><option value="repaired">Giderildi · Avukat beyanı</option><option value="withheld" disabled={comparison.candidate_disposition !== 'withheld'}>Sonuç bekletildi</option><option value="unresolved">Çözülmedi</option></select>}</Field><Field label={`Önceki bulgu ${finding.finding_index + 1} gerekçesi`}>{(id) => <textarea id={id} rows={2} maxLength={2000} value={item.note} disabled={busy} onChange={(event) => disposition(index, { note: event.target.value })} />}</Field><ReferencePicker value={item} onChange={(change) => disposition(index, change)} comparison={comparison} busy={busy} /></Detail>; })}
    <Field label="Beyan edilen inceleme süresi · saniye (isteğe bağlı)" hint="Bu karşılaştırma için kaynak okuma, doğrulama ve düzeltme incelemesine harcadığınız süre. Otomatik kronometre veya zaman kazanımı ölçümü değildir.">{(id) => <input id={id} type="number" min={1} max={28800} step={1} value={value.review_seconds} disabled={busy} onChange={(event) => onChange({ ...value, review_seconds: event.target.value })} />}</Field>
  </>;
}

export function RevisionAssessmentDetails({ assessment, comparison, onSource }: { assessment: RevisionAssessment; comparison: RevisionComparison; onSource: (id: string) => void }) {
  function links(item: LinkedObservation) { return <><p className="reference-id">İncelenen adımlar: {item.target_ids.join(', ')}</p>{item.source_refs.map((ref) => { const source = comparison.sources.find((candidate) => candidate.source_ref === ref); return source ? <button key={ref} type="button" className="source-link" onClick={() => onSource(source.evidence_id)}>{ref.startsWith('before:') ? 'Önceki' : comparison.candidate_kind ? 'Model adayı' : 'Gösterilen'} · {source.name} · [{source.start}, {source.end})</button> : null; })}{!item.source_refs.length && <p className="small muted">Alıntı bağlanmadı</p>}</>; }
  return <Detail title={comparison.candidate_kind ? 'Kaydedilmiş kaynak bağlı aday değerlendirmesi' : 'Kaydedilmiş kaynak bağlı sürüm değerlendirmesi'}><p className="small muted">Karşılaştırma kayıt anındaki sürüm ve dayanakları gösterir. Güncel inceleme durumu yukarıda ayrıca belirtilir.</p><RevisionComparisonDetails comparison={comparison} onSource={onSource} /><p>Beyan edilen inceleme süresi: {assessment.review_seconds === null ? 'Ölçülmedi' : `${assessment.review_seconds} saniye`}. Önceki bulgular korunur; beyanlar bu karşılaştırmaya aittir.</p><Detail title={`Anlamsal gözlemler (${assessment.observations.length})`}>{assessment.observations.map((item) => <Detail key={item.dimension} title={`${SEMANTIC_LABELS[item.dimension]} · ${OUTCOMES[item.outcome]}`}><p className="authored-text">{item.note}</p>{links(item)}</Detail>)}</Detail>{assessment.finding_dispositions.map((item) => { const finding = comparison.findings.find((candidate) => candidate.finding_index === item.finding_index); return <Detail key={item.finding_index} title={`Önceki bulgu ${item.finding_index + 1} · ${OUTCOMES[item.outcome]}`}><p className="authored-text"><strong>Önceki bulgu · {finding?.target_id}:</strong> {finding?.text}</p>{finding?.suggested_change && <p>İstenen değişiklik: {finding.suggested_change}</p>}<p className="authored-text"><strong>Bu karşılaştırmadaki avukat beyanı:</strong> {item.note}</p>{links(item)}</Detail>; })}</Detail>;
}
