import { useEffect, useRef, useState } from 'react';
import { ApiError, downloadAuthorityAdjudication, post, request } from '../../api';
import { Badge, Detail, Field, Notice } from '../../components';
import { formatDate, messageOf } from '../../utils';
import { ComparisonEvidence } from './AuthorityComparisons';
import { DISPOSITIONS } from './authorityComparisonTypes';
import { adjudicationAssessment, committedAdjudicationReceipt, JUDGMENT_OUTCOMES, SEMANTIC_DIMENSIONS, SEMANTIC_OUTCOMES } from './authorityAdjudicationTypes';
import type { AdjudicationInputs, AdjudicationLinks, AdjudicationView, AdverseScope, FindingJudgment, SemanticObservation } from './authorityAdjudicationTypes';
import type { FindingSummary } from './authorityFindingTypes';

const blankLinks = (): AdjudicationLinks => ({ note: '', target_refs: [], private_source_refs: [], public_source_indices: [] });

export function AdjudicationContent({ value }: { value: AdjudicationView }) {
  const data = value.public_source_access ? value.snapshot : null;
  return <><p className="small">{value.reviewer_name} · kendi {value.sequence}. değerlendirmesi · {formatDate(value.recorded_at, true)}</p>
    <Badge status={value.freshness.status}>{value.freshness.status === 'current' ? 'Değerlendirme bağları güncel' : value.freshness.status === 'stale' ? 'Yeniden inceleme gerekli · Aktarım kapalı' : 'İçerik bekletiliyor'}</Badge>
    {!data ? <Notice error>Kaynak izinleri veya kayıt tamamlaması doğrulanamadı. Tüm değerlendirme notları ve alıntılar bekletiliyor.</Notice> : <>
      <p className="authored-text">{data.assessment.note}</p><p className="small">Beyan edilen değerlendirme kapsamı: anlam {data.coverage.semantic.assessed}/{data.coverage.semantic.total} · bulgular {data.coverage.findings.assessed}/{data.coverage.findings.total}. Bu sayılar doğruluk puanı değildir. Derlem bütünlüğü bilinmiyor; karşı dayanak bulma kapsamı ölçülmedi.</p>
      <p className="small">Beyan edilen süre: {data.assessment.review_seconds === null ? 'Ölçülmedi' : `${data.assessment.review_seconds} saniye`}. Hesap ayrılığı mesleki yeterlilik veya gerçek bağımsızlık belgesi değildir.</p>
      <Detail title="Anlam ve mantık gözlemleri">{data.assessment.observations.map(item => <section key={item.dimension}><h4>{data.basis.dimensions[item.dimension]} · {item.outcome && SEMANTIC_OUTCOMES[item.outcome]}</h4><p className="authored-text">{item.note}</p><p className="small">{item.target_refs.join(' · ')} · {item.private_source_refs.join(' · ')} · Kamu kaynakları: {item.public_source_indices.map(i => i + 1).join(', ') || 'Bağlanmadı'}</p></section>)}</Detail>
      <Detail title="Her karşılaştırma beyanına verilen ayrı görüş">{data.assessment.judgments.map(item => <section key={`${item.source_index}:${item.dimension}`}><h4>{item.source_index + 1}. kaynak · {data.basis.comparison.comparison_snapshot.dimensions[item.dimension]} · {item.outcome && JUDGMENT_OUTCOMES[item.outcome]}</h4><p className="authored-text">{item.note}</p><p className="small">{item.target_refs.join(' · ')} · {item.private_source_refs.join(' · ')} · Kamu kaynakları: {item.public_source_indices.map(i => i + 1).join(', ') || 'Bağlanmadı'}</p></section>)}</Detail>
      <Detail title="Karşı dayanak incelemesinin sınırları"><p>{data.assessment.adverse_scope.status === 'not_searched' ? 'Araştırılmadı' : 'Yalnız seçili kaynaklar incelendi'}</p><p>İncelenen kaynaklar: {data.assessment.adverse_scope.inspected_source_indices.map(i => i + 1).join(', ') || 'Yok'}</p><p className="authored-text">{data.assessment.adverse_scope.limitations}</p></Detail>
      <ComparisonEvidence comparison={data.basis.comparison.comparison_snapshot} />
    </>}<Detail title="Değerlendirme kimliği ve güncellik"><p className="reference-id">{value.id} · {value.adjudication_sha256}</p><p>{value.freshness.reasons.join(' · ') || 'Teknik bağlar güncel; hukuki onay verilmez.'}</p></Detail></>;
}

function LinkFields({ inputs, value, onChange }: { inputs: AdjudicationInputs; value: AdjudicationLinks; onChange: (change: Partial<AdjudicationLinks>) => void }) {
  const comp = inputs.basis.comparison.comparison_snapshot;
  return <><Field label="Açıklama">{id => <textarea id={id} maxLength={2000} value={value.note} onChange={event => onChange({ note: event.target.value })} />}</Field>
    <Field label="İncelenen önceki / yeni adımlar">{id => <select id={id} multiple value={value.target_refs} onChange={event => onChange({ target_refs: Array.from(event.target.selectedOptions, item => item.value) })}>{(['before', 'after'] as const).flatMap(side => Object.keys(comp[`${side}_targets`]).map(key => <option key={`${side}:${key}`} value={`${side}:${key}`}>{side === 'before' ? 'Önceki' : 'Yeni'} · {key}</option>))}</select>}</Field>
    <Field label="Özel belge alıntıları">{id => <select id={id} multiple value={value.private_source_refs} onChange={event => onChange({ private_source_refs: Array.from(event.target.selectedOptions, item => item.value) })}>{comp.private_sources.map(item => <option key={item.source_ref} value={item.source_ref}>{item.source_ref}</option>)}</select>}</Field>
    <Field label="Özgün kamu kaynakları">{id => <select id={id} multiple value={value.public_source_indices.map(String)} onChange={event => onChange({ public_source_indices: Array.from(event.target.selectedOptions, item => Number(item.value)) })}>{comp.authority_review_snapshot.assessment.sources.map((source, index) => <option key={index} value={index}>{index + 1}. kaynak · {source.authority_id}</option>)}</select>}</Field></>;
}

function Editor({ inputs, base, onSaved, onUnavailable }: { inputs: AdjudicationInputs; base: string; onSaved: (pending: boolean) => void; onUnavailable: (cause: unknown) => void }) {
  const [observations, setObservations] = useState<SemanticObservation[]>(() => SEMANTIC_DIMENSIONS.map(dimension => ({ dimension, outcome: '', ...blankLinks() })));
  const [judgments, setJudgments] = useState<FindingJudgment[]>(() => inputs.basis.comparison.assessment.dispositions.map(item => ({ source_index: item.source_index, dimension: item.dimension, outcome: '', ...blankLinks() })));
  const [scope, setScope] = useState<AdverseScope>({ status: '', inspected_source_indices: [], limitations: '' });
  const [note, setNote] = useState(''); const [seconds, setSeconds] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const mounted = useRef(true); useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const nonce = useRef<{ body: string; id: string } | null>(null);
  const assessment = adjudicationAssessment(inputs, observations, judgments, scope, note, seconds);
  async function save() {
    if (!assessment) return; setBusy(true); setError('');
    const spec = { ...assessment, expected_basis_sha256: inputs.basis_sha256, expected_adjudication_id: inputs.expected_adjudication_id }; const key = JSON.stringify(spec);
    if (nonce.current?.body !== key) nonce.current = { body: key, id: crypto.randomUUID().replaceAll('-', '') };
    try { await post(base, { ...spec, request_id: nonce.current.id }); if (mounted.current) onSaved(false); }
    catch (cause) { if (mounted.current) { if (cause instanceof ApiError && committedAdjudicationReceipt(cause.data)) onSaved(true); else if (cause instanceof ApiError && cause.status !== 0) onUnavailable(cause); else setError(messageOf(cause)); } }
    finally { if (mounted.current) setBusy(false); }
  }
  if (!inputs.can_record) return <Notice error>{!inputs.independent_account ? 'Taslak, özgün inceleme ve karşılaştırma yazarından ayrı avukat hesabı gerekli.' : 'Dayanaklar güncel değil veya çalışma alanı arşivlendi.'}</Notice>;
  return <form className="authority-context-form" onSubmit={event => { event.preventDefault(); void save(); }}><ComparisonEvidence comparison={inputs.basis.comparison.comparison_snapshot} />
    <p className="small">Anlam ve mantık gözlemleri ile her özgün karşılaştırma beyanı için ayrı görüş kaydedin. Destek ve görüşler kaynak/adım bağlantısı gerektirir; tam karşı içtihat araştırması veya hukuki onay oluşturmaz.</p>
    <fieldset disabled={busy}>{observations.map((item, index) => <Detail key={item.dimension} title={inputs.basis.dimensions[item.dimension]}><Field label="Anlam / mantık görüşü">{id => <select id={id} value={item.outcome} onChange={event => setObservations(old => old.map((row, i) => i === index ? { ...row, outcome: event.target.value as SemanticObservation['outcome'] } : row))}><option value="">Görüş seçin</option>{Object.entries(SEMANTIC_OUTCOMES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>}</Field><LinkFields inputs={inputs} value={item} onChange={change => setObservations(old => old.map((row, i) => i === index ? { ...row, ...change } : row))} /></Detail>)}
      {judgments.map((item, index) => { const prior = inputs.basis.comparison.assessment.dispositions[index]; return <Detail key={`${item.source_index}:${item.dimension}`} title={`${item.source_index + 1}. kaynak · ${inputs.basis.comparison.comparison_snapshot.dimensions[item.dimension]}`}><p>Karşılaştırma beyanı: {DISPOSITIONS[prior.outcome]}</p><p className="authored-text">{prior.note}</p><Field label="Bu beyana ilişkin görüş">{id => <select id={id} value={item.outcome} onChange={event => setJudgments(old => old.map((row, i) => i === index ? { ...row, outcome: event.target.value as FindingJudgment['outcome'] } : row))}><option value="">Görüş seçin</option>{Object.entries(JUDGMENT_OUTCOMES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>}</Field><LinkFields inputs={inputs} value={item} onChange={change => setJudgments(old => old.map((row, i) => i === index ? { ...row, ...change } : row))} /></Detail>; })}
      <Field label="Karşı dayanak araştırmasının kapsamı">{id => <select id={id} value={scope.status} onChange={event => setScope(old => ({ ...old, status: event.target.value as AdverseScope['status'], inspected_source_indices: [] }))}><option value="">Kapsam seçin</option><option value="not_searched">Araştırılmadı</option><option value="selected_sources_inspected">Yalnız seçili kaynaklar incelendi</option></select>}</Field>
      {scope.status === 'selected_sources_inspected' && <Field label="İncelenen kaynaklar">{id => <select id={id} multiple value={scope.inspected_source_indices.map(String)} onChange={event => setScope(old => ({ ...old, inspected_source_indices: Array.from(event.target.selectedOptions, item => Number(item.value)) }))}>{inputs.basis.comparison.comparison_snapshot.authority_review_snapshot.assessment.sources.map((_, i) => <option key={i} value={i}>{i + 1}. kaynak</option>)}</select>}</Field>}
      <Field label="Araştırma sınırları ve eksikler">{id => <textarea id={id} maxLength={2000} value={scope.limitations} onChange={event => setScope(old => ({ ...old, limitations: event.target.value }))} />}</Field>
      <Field label="Genel değerlendirme notu">{id => <textarea id={id} maxLength={2000} value={note} onChange={event => setNote(event.target.value)} />}</Field>
      <Field label="Etkin inceleme süresi (saniye, isteğe bağlı)">{id => <input id={id} type="number" min={1} max={28800} step={1} value={seconds} placeholder="Ölçülmedi" onChange={event => setSeconds(event.target.value)} />}</Field>
      <button className="button" type="submit" disabled={!assessment}>Ayrı görüşü kaydet</button></fieldset>{error && <Notice error>{error}</Notice>}</form>;
}

export default function AuthorityAdjudications({ base, onUnavailable }: { base: string; onUnavailable: (cause: unknown) => void }) {
  const [inputs, setInputs] = useState<AdjudicationInputs | null>(null); const [items, setItems] = useState<FindingSummary[]>([]); const [view, setView] = useState<AdjudicationView | null>(null); const [busy, setBusy] = useState(false); const [more, setMore] = useState(false); const [loaded, setLoaded] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const mounted = useRef(true); useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  function fail(cause: unknown) { setInputs(null); setView(null); setItems([]); setError(messageOf(cause)); onUnavailable(cause); }
  async function load() { setInputs(null); setView(null); setBusy(true); setError(''); try { const value = await request<AdjudicationInputs>(`${base}/context`, { cache: 'no-store' }); if (mounted.current) setInputs(value); } catch (cause) { if (mounted.current) fail(cause); } finally { if (mounted.current) setBusy(false); } }
  async function history(append = false) { setInputs(null); setView(null); setBusy(true); setError(''); try { const page = await request<FindingSummary[]>(`${base}?limit=10&offset=${append ? items.length : 0}`, { cache: 'no-store' }); if (mounted.current) { setItems(old => append ? [...old, ...page.filter(item => !old.some(prior => prior.id === item.id))] : page); setLoaded(true); setMore(page.length === 10); } } catch (cause) { if (mounted.current) fail(cause); } finally { if (mounted.current) setBusy(false); } }
  async function inspect(id: string) { setInputs(null); setView(null); setBusy(true); setError(''); try { const value = await request<AdjudicationView>(`${base}/${encodeURIComponent(id)}`, { cache: 'no-store' }); if (mounted.current) { if (!value.public_source_access) fail(new Error('Değerlendirme içeriği bekletiliyor; kaynak bağlamını yeniden açın.')); else setView(value); } } catch (cause) { if (mounted.current) fail(cause); } finally { if (mounted.current) setBusy(false); } }
  async function download(format: 'json' | 'docx' | 'pdf') { if (!view) return; setBusy(true); try { await downloadAuthorityAdjudication(base, view.id, format); } catch (cause) { if (mounted.current) fail(cause); } finally { if (mounted.current) setBusy(false); } }
  return <><p className="small">Ayrı avukat hesabından anlam ve karşı dayanak değerlendirmesi. Her inceleyenin görüşü korunur; görüş birliği ve hukuki onay otomatik hesaplanmaz.</p><div className="practice-record-actions"><button className="text-button" disabled={busy} onClick={() => void load()}>Ayrı değerlendirme girdilerini getir</button><button className="text-button" disabled={busy} onClick={() => void history()}>Tüm inceleyenlerin görüşlerini getir</button></div>
    {notice && <Notice>{notice}</Notice>}{inputs && <Editor key={inputs.basis_sha256 + (inputs.expected_adjudication_id || '')} inputs={inputs} base={base} onUnavailable={fail} onSaved={pending => { setInputs(null); setNotice(pending ? 'Kayıt saklandı; son izin kontrolü tamamlanmadı. İçerik bekletiliyor.' : 'Ayrı görüş kaydedildi; saklanan kaydı açarak bağları kontrol edin.'); void history(); }} />}
    {items.map(item => <Detail key={item.id} title={`${item.reviewer_name} · kendi ${item.sequence}. görüşü`}><button className="text-button" disabled={busy} onClick={() => void inspect(item.id)}>Görüşü aç / bağları kontrol et</button>{view?.id === item.id && <><AdjudicationContent value={view} /><div className="practice-record-actions">{(['json', 'docx', 'pdf'] as const).map(format => <button key={format} className="text-button" disabled={busy || view.freshness.status !== 'current'} onClick={() => void download(format)}>{format.toUpperCase()} değerlendirmeyi indir</button>)}</div></>}</Detail>)}
    {loaded && !items.length && <p>Bu karşılaştırmaya bağlı ayrı görüş yok.</p>}{more && <button className="text-button" disabled={busy} onClick={() => void history(true)}>Önceki görüşleri getir</button>}{error && <Notice error>{error}</Notice>}</>;
}
