import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { downloadPracticeDraft, post, request } from '../../api';
import { Badge, Detail, Field, Icon, JsonDetails, Loading, Notice } from '../../components';
import type { AuthorityReference, DocumentRecord, Matter, Passage, PracticeKind, PracticeRecord, PracticeVersion } from '../../types';
import { DOMAIN_LABELS, formatDate, locatorText, messageOf } from '../../utils';
import { EvidenceViewer } from './FactsPanel';

const LABELS: Record<PracticeKind, string> = { scenarios: 'Senaryolar', contradictions: 'Çelişki kaydı', arguments: 'Argüman matrisi', drafts: 'Hazırlık taslakları ve inceleme notları' };
const DESCRIPTIONS: Record<PracticeKind, string> = {
  scenarios: 'Varsayımlar ayrı kaydedilir; olgu defteri değiştirilmez. Bir senaryo kurmak, varsayımın doğru olduğunu göstermez.',
  contradictions: 'İki farklı olgu arasındaki uyuşmazlığı ve değerlendirme gerekçenizi kaydedin. Çelişkiyi çözmek, özgün olguları değiştirmez.',
  arguments: 'Destekleyen, karşı ve alternatif argümanları bir hukuki mesele altında toplayın. Yerel pasaj veya kayıtlı kamu kaynak adayı bağlayın.',
  drafts: 'Kendi hazırlık metninizi ve inceleme notunuzu yazın. Her değişiklik yeni ve değiştirilemez bir sürüm olarak saklanır.',
};
const KIND_LIST = Object.keys(LABELS) as PracticeKind[];
const STATUS: Record<string, string> = { active: 'Etkin', retired: 'Kullanımdan kaldırıldı', open: 'Açık', resolved: 'Değerlendirildi', dismissed: 'Çelişki olarak görülmedi', working: 'Çalışma halinde', ready_for_review: 'İncelemeye hazır', withdrawn: 'Geri çekildi', supporting: 'Destekleyen', adverse: 'Karşı', alternative: 'Alternatif', draft: 'Taslak', curated: 'Küratör incelemesinden geçti', preparation: 'Hazırlık taslağı', review_note: 'İnceleme notu' };
type Lists = Record<PracticeKind | 'playbooks' | 'library', PracticeRecord[]>;
const emptyLists = (): Lists => ({ scenarios: [], contradictions: [], arguments: [], drafts: [], playbooks: [], library: [] });
type Editor = { kind: PracticeKind; record?: PracticeRecord } | null;

export default function PracticePanel({ matter, onChange, userRole }: { matter: Matter; onChange: () => Promise<void>; userRole: string }) {
  const [data, setData] = useState<Lists>(emptyLists); const [loading, setLoading] = useState(true); const [errors, setErrors] = useState<Record<string, string>>({});
  const [editor, setEditor] = useState<Editor>(null); const [notice, setNotice] = useState(''); const [source, setSource] = useState<string | null>(null);
  const base = `/matters/${encodeURIComponent(matter.id)}/practice`;
  const load = useCallback(async () => {
    const keys = [...KIND_LIST, 'playbooks', 'library'] as (keyof Lists)[];
    const results = await Promise.allSettled(keys.map((key) => request<PracticeRecord[]>(key === 'library' ? '/playbooks?limit=100' : `${base}/${key}?limit=100`)));
    const nextErrors: Record<string, string> = {};
    results.forEach((result, index) => { const key = keys[index]; if (result.status === 'fulfilled') setData((old) => ({ ...old, [key]: result.value })); else { nextErrors[key] = messageOf(result.reason); setData((old) => ({ ...old, [key]: [] })); } });
    setErrors(nextErrors); setLoading(false);
  }, [base]);
  useEffect(() => { void load(); }, [load]);
  async function saved() { setEditor(null); setNotice('Yeni kayıt veya sürüm saklandı. Önceki sürümler korunur; mevcut hazırlık çıktılarını yeniden inceleyin.'); await load(); await onChange(); }
  return <section><div className="section-heading"><div><h2>Avukatın çalışma defteri</h2><p className="small muted">Bu bölümdeki metinler sizin katkınızdır; model tarafından üretilmiş veya hukuken doğrulanmış sonuç değildir.</p></div><button className="button secondary" onClick={() => void load()}>Yenile</button></div>
    {notice && <Notice>{notice}</Notice>}
    {loading ? <Loading label="Çalışma notları açılıyor…" /> : KIND_LIST.map((kind) => <Detail key={kind} title={`${LABELS[kind]} (${data[kind].length})`}>
      <div className="practice-section-intro"><p>{DESCRIPTIONS[kind]}</p><button className="button secondary" onClick={() => { setEditor({ kind }); setNotice(''); }}><Icon name="plus" size={16} />{kind === 'scenarios' ? 'Senaryo ekle' : kind === 'contradictions' ? 'Çelişki bağla' : kind === 'arguments' ? 'Argüman ekle' : 'Taslak yaz'}</button></div>
      {errors[kind] && <Notice error>{errors[kind]}</Notice>}
      {editor?.kind === kind && <PracticeEditor kind={kind} key={editor.record?.id || `new-${kind}`} record={editor.record} matter={matter} onCancel={() => setEditor(null)} onSave={saved} />}
      {!errors[kind] && !data[kind].length && editor?.kind !== kind && <p className="practice-empty">Henüz kayıt yok. Yukarıdaki düğmeyle avukat çalışma kaydı ekleyin.</p>}
      <div className="practice-record-list">{data[kind].map((record) => <article className="practice-record" key={record.id}>
        <div className="practice-record-heading"><div><h3>{record.title || record.issue || 'Olgular arası çelişki'}</h3><span className="small muted">Sürüm {record.version} · {formatDate(record.updated_at || record.created_at, true)}</span></div><Badge>{STATUS[record.position || record.status || 'working'] || record.status}</Badge></div>
        <PracticeContent record={record} />
        {record.evidence_snapshots?.length ? <div className="claim-sources">{record.evidence_snapshots.map((evidence) => <button key={evidence.id} className="source-link" onClick={() => setSource(evidence.id)}><Icon name="file" size={14} />{evidence.name} · {locatorText(evidence.locator)}</button>)}</div> : null}
        {record.authority_snapshots?.length ? <Detail title="Bağlı kamu kaynak adayları"><p className="small muted">Kaynak bağlantısı, hukuki uygulanabilirlik onayı değildir.</p>{record.authority_snapshots.map((ref, index) => <p className="reference-id" key={index}>{ref.authority_id} · {ref.source_version_id} · {ref.passage_id}</p>)}</Detail> : null}
        <div className="practice-record-actions"><button className="text-button" onClick={() => { setEditor({ kind, record }); setNotice(''); }}><Icon name="edit" size={15} />Yeni sürüm yaz</button>{kind === 'drafts' && <DraftDownloads matterId={matter.id} recordId={record.id} versionId={record.latest_version_id} />}</div>
        <VersionHistory endpoint={`${base}/${kind}/${encodeURIComponent(record.id)}/versions`} matterId={matter.id} draftId={kind === 'drafts' ? record.id : undefined} />
      </article>)}</div>
      {data[kind].length === 100 && <p className="small muted">En yeni 100 kayıt gösteriliyor.</p>}
    </Detail>)}
    {!loading && <Detail title={`Kurum rehberleri (${data.playbooks.length} benimsenmiş sürüm)`}><Playbooks matterId={matter.id} library={data.library} adopted={data.playbooks} canCurate={['admin', 'curator'].includes(userRole)} onSave={saved} error={errors.playbooks || errors.library} /></Detail>}
    {source && <EvidenceViewer key={source} matter={matter} evidenceId={source} onClose={() => setSource(null)} />}
  </section>;
}

function PracticeContent({ record }: { record: PracticeRecord }) {
  return <div className="practice-content">{record.assumptions?.length ? <><span className="small-label">YALNIZCA SENARYO VARSAYIMLARI</span><ol>{record.assumptions.map((item, index) => <li key={index}>{item}</li>)}</ol></> : null}{record.text && <p className="authored-text">{record.text}</p>}{record.reason && <p><strong>Gerekçe:</strong> {record.reason}</p>}{record.notes && <p className="authored-text">{record.notes}</p>}{record.review_note && <p className="review-note"><strong>Avukatın inceleme notu:</strong> {record.review_note}</p>}{record.fact_snapshots?.length ? <Detail title="Kaydedildiği anda bağlı olgular"><ul>{record.fact_snapshots.map((fact) => <li key={fact.id}>{fact.text}<span className="small muted"> · Olgu sürümü {fact.revision}</span></li>)}</ul><p className="small muted">Bu kayıt olgu defterini değiştirmez. Güncel olgular ayrı bölümden incelenir.</p></Detail> : null}</div>;
}

interface FormState {
  title: string; text: string; assumptions: string; fact_ids: string[]; notes: string; status: string; reason: string;
  issue: string; position: string; evidence_ids: string[]; authority_refs: AuthorityReference[];
  draft_kind: string; review_note: string; change_note: string;
}
function PracticeEditor({ kind, record, matter, onCancel, onSave }: { kind: PracticeKind; record?: PracticeRecord; matter: Matter; onCancel: () => void; onSave: () => Promise<void> }) {
  const [form, setForm] = useState<FormState>({ title: record?.title || '', text: record?.text || '', assumptions: record?.assumptions?.join('\n') || '', fact_ids: record?.fact_ids || [], notes: record?.notes || '', status: record?.status || (kind === 'scenarios' ? 'active' : kind === 'contradictions' ? 'open' : 'working'), reason: record?.reason || '', issue: record?.issue || '', position: record?.position || 'supporting', evidence_ids: record?.evidence_ids || [], authority_refs: record?.authority_refs || [], draft_kind: record?.draft_kind || 'preparation', review_note: record?.review_note || '', change_note: '' });
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((old) => ({ ...old, [key]: value }));
  const statuses = kind === 'scenarios' ? ['active', 'retired'] : kind === 'contradictions' ? ['open', 'resolved', 'dismissed'] : ['working', 'ready_for_review', 'withdrawn'];
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError('');
    const payload = kind === 'scenarios' ? { title: form.title, assumptions: form.assumptions.split('\n').map((line) => line.trim()).filter(Boolean), fact_ids: form.fact_ids, notes: form.notes, status: form.status } : kind === 'contradictions' ? { fact_ids: form.fact_ids, reason: form.reason, status: form.status } : kind === 'arguments' ? { issue: form.issue, position: form.position, text: form.text, evidence_ids: form.evidence_ids, authority_refs: form.authority_refs, status: form.status } : { title: form.title, draft_kind: form.draft_kind, text: form.text, review_note: form.review_note, status: form.status };
    const base = `/matters/${encodeURIComponent(matter.id)}/practice/${kind}`;
    try { await post(record ? `${base}/${encodeURIComponent(record.id)}/versions` : base, { ...payload, ...(record ? { expected_revision: record.revision, change_note: form.change_note } : {}) }); await onSave(); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); }
  }
  return <form className="inline-form form-grid" onSubmit={submit} aria-label={`${LABELS[kind]} düzenleyicisi`}><div className="span-full"><h3>{record ? `Sürüm ${record.version + 1} · Önceki sürüm korunacak` : `Yeni kayıt · ${LABELS[kind]}`}</h3><p className="small muted">İçeriği siz yazıyorsunuz. Kaydetme, hukuki doğrulama veya otomatik olgu değişikliği yapmaz.</p></div>{error && <div className="span-full"><Notice error>{error}</Notice></div>}
    {(kind === 'scenarios' || kind === 'drafts') && <Field label="Başlık" className="span-full">{(id) => <input id={id} autoFocus required maxLength={200} value={form.title} onChange={(event) => update('title', event.target.value)} />}</Field>}
    {kind === 'scenarios' && <><Field label="Varsayımlar · her satıra bir varsayım" className="span-full" hint="En fazla 20 varsayım. Bu bilgiler olgu defterine yazılmaz.">{(id) => <textarea id={id} required rows={4} value={form.assumptions} onChange={(event) => update('assumptions', event.target.value)} />}</Field><fieldset className="reference-picker span-full"><legend>İlgili olgular · isteğe bağlı</legend>{matter.facts?.length ? matter.facts.map((fact) => <label className="checkbox-label" key={fact.id}><input type="checkbox" checked={form.fact_ids.includes(fact.id)} onChange={(event) => update('fact_ids', event.target.checked ? [...form.fact_ids, fact.id] : form.fact_ids.filter((item) => item !== fact.id))} /><span>{fact.text}</span></label>) : <p className="small muted">Olgu defterinde kayıt yok.</p>}</fieldset><Field label="Senaryo notu" className="span-full">{(id) => <textarea id={id} maxLength={4000} rows={2} value={form.notes} onChange={(event) => update('notes', event.target.value)} />}</Field></>}
    {kind === 'contradictions' && <>{[0, 1].map((index) => <Field key={index} label={`${index + 1}. olgu`}>{(id) => <select id={id} required value={form.fact_ids[index] || ''} onChange={(event) => { const ids = [...form.fact_ids]; ids[index] = event.target.value; update('fact_ids', ids); }}><option value="">Olgu seçin</option>{matter.facts?.map((fact) => <option key={fact.id} value={fact.id}>{fact.text.slice(0, 130)}</option>)}</select>}</Field>)}<Field label="Çelişki veya değerlendirme gerekçesi" className="span-full">{(id) => <textarea id={id} required minLength={3} maxLength={4000} rows={3} value={form.reason} onChange={(event) => update('reason', event.target.value)} />}</Field></>}
    {kind === 'arguments' && <><Field label="Hukuki mesele" className="span-full">{(id) => <input id={id} required minLength={3} maxLength={1000} value={form.issue} onChange={(event) => update('issue', event.target.value)} />}</Field><Field label="Argümanın yönü">{(id) => <select id={id} value={form.position} onChange={(event) => update('position', event.target.value)}>{['supporting', 'adverse', 'alternative'].map((value) => <option key={value} value={value}>{STATUS[value]}</option>)}</select>}</Field><div className="span-full"><EvidencePicker matter={matter} evidenceIds={form.evidence_ids} authorityRefs={form.authority_refs} onEvidence={(ids) => update('evidence_ids', ids)} onAuthorities={(refs) => update('authority_refs', refs)} /></div></>}
    {kind === 'drafts' && <Field label="Çalışma türü">{(id) => <select id={id} value={form.draft_kind} onChange={(event) => update('draft_kind', event.target.value)}><option value="preparation">Hazırlık taslağı</option><option value="review_note">İnceleme notu</option></select>}</Field>}
    {(kind === 'drafts' || kind === 'arguments') && <Field label={kind === 'drafts' ? 'Avukatın hazırladığı metin' : 'Argüman metni'} className="span-full">{(id) => <textarea id={id} required minLength={kind === 'arguments' ? 3 : 1} maxLength={kind === 'drafts' ? 30000 : 8000} rows={kind === 'drafts' ? 9 : 4} value={form.text} onChange={(event) => update('text', event.target.value)} />}</Field>}
    {kind === 'drafts' && <Field label="İnceleme notunuz" className="span-full">{(id) => <textarea id={id} maxLength={4000} rows={2} value={form.review_note} onChange={(event) => update('review_note', event.target.value)} />}</Field>}
    <Field label="Çalışma durumu">{(id) => <select id={id} value={form.status} onChange={(event) => update('status', event.target.value)}>{statuses.map((value) => <option key={value} value={value}>{STATUS[value]}</option>)}</select>}</Field>
    {record && <Field label="Bu sürümde ne değişti?" className="span-full">{(id) => <textarea id={id} required minLength={3} maxLength={2000} rows={2} value={form.change_note} onChange={(event) => update('change_note', event.target.value)} />}</Field>}
    <div className="form-actions span-full"><button type="button" className="button secondary" onClick={onCancel}>Vazgeç</button><button className="button primary" disabled={busy}>{busy ? 'Kaydediliyor…' : record ? 'Yeni sürümü kaydet' : 'Çalışma kaydını ekle'}</button></div>
  </form>;
}

function EvidencePicker({ matter, evidenceIds, authorityRefs, onEvidence, onAuthorities }: { matter: Matter; evidenceIds: string[]; authorityRefs: AuthorityReference[]; onEvidence: (ids: string[]) => void; onAuthorities: (refs: AuthorityReference[]) => void }) {
  const [documentId, setDocumentId] = useState(''); const [passages, setPassages] = useState<Passage[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!documentId) { setPassages([]); return; } const controller = new AbortController(); setLoading(true); setError(''); request<DocumentRecord>(`/matters/${encodeURIComponent(matter.id)}/documents/${encodeURIComponent(documentId)}`, { signal: controller.signal }).then((data) => setPassages(data.passages || [])).catch((cause) => { if (!controller.signal.aborted) setError(messageOf(cause)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [documentId, matter.id]);
  const candidates = (matter.products || []).flatMap((product) => (product.authority_candidates?.hits || []).map((hit) => ({ product_id: product.id, hit })));
  return <fieldset className="reference-picker"><legend>Argüman dayanakları · en az bir kaynak</legend><Field label="Yerel belge">{(id) => <select id={id} value={documentId} onChange={(event) => setDocumentId(event.target.value)}><option value="">Belge seçin</option>{matter.documents?.map((doc) => <option key={doc.id} value={doc.id}>{doc.name}</option>)}</select>}</Field>{error && <Notice error>{error}</Notice>}{loading ? <Loading label="Pasajlar yükleniyor…" /> : <div className="reference-options">{passages.map((passage) => <label className="checkbox-label" key={passage.id}><input type="checkbox" checked={evidenceIds.includes(passage.id)} onChange={(event) => onEvidence(event.target.checked ? [...evidenceIds, passage.id] : evidenceIds.filter((id) => id !== passage.id))} /><span><strong>{locatorText(passage.locator)}</strong><span>{passage.text.slice(0, 240)}</span></span></label>)}</div>}{evidenceIds.length > 0 && <Detail title={`Seçili yerel dayanaklar (${evidenceIds.length})`}>{evidenceIds.map((id) => <div className="selected-reference" key={id}><span className="reference-id">{id}</span><button type="button" className="text-button" onClick={() => onEvidence(evidenceIds.filter((item) => item !== id))}>Kaldır</button></div>)}</Detail>}{candidates.length > 0 && <Detail title="Dosyada kaydedilmiş kamu kaynak adayları"><p className="small muted">Aday seçimi, hukuki uygulanabilirlik onayı değildir.</p>{candidates.map(({ product_id, hit }) => <label className="checkbox-label" key={`${product_id}:${hit.passage_id}`}><input type="checkbox" checked={authorityRefs.some((ref) => ref.product_id === product_id && ref.passage_id === hit.passage_id)} onChange={(event) => onAuthorities(event.target.checked ? [...authorityRefs, { product_id, passage_id: hit.passage_id }] : authorityRefs.filter((ref) => ref.product_id !== product_id || ref.passage_id !== hit.passage_id))} /><span>{hit.title} · {locatorText(hit.locator)}</span></label>)}</Detail>}</fieldset>;
}

function VersionHistory({ endpoint, matterId, draftId }: { endpoint: string; matterId?: string; draftId?: string }) {
  const [versions, setVersions] = useState<PracticeVersion[] | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { setBusy(true); setError(''); try { setVersions(await request<PracticeVersion[]>(`${endpoint}?limit=100`)); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  return <div className="version-history"><button className="text-button" onClick={() => versions ? setVersions(null) : void load()} disabled={busy}><Icon name="clock" size={15} />{busy ? 'Sürümler yükleniyor…' : versions ? 'Sürüm geçmişini kapat' : 'Sürüm geçmişini göster'}</button>{error && <Notice error>{error}</Notice>}{versions && <><p className="small muted">Bu kayıtlar değiştirilemez. Bir metni güncellemek için yeni sürüm yazın.</p>{versions.map((version) => <Detail key={version.id} title={`Sürüm ${version.version} · ${formatDate(version.created_at, true)}`}><PracticeContent record={version.content} />{version.change_note && <p className="review-note"><strong>Değişiklik gerekçesi:</strong> {version.change_note}</p>}{draftId && matterId && <DraftDownloads matterId={matterId} recordId={draftId} versionId={version.id} />}<JsonDetails title="Sürüm kimliği ve yazar kaydı" value={{ version_id: version.id, authored_by: version.authored_by, immutable: version.immutable, status: version.content.status, curation_status: version.content.curation_status }} /></Detail>)}{versions.length === 100 && <p className="small muted">En yeni 100 sürüm gösteriliyor.</p>}</>}</div>;
}

function DraftDownloads({ matterId, recordId, versionId }: { matterId: string; recordId: string; versionId: string }) {
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  async function download(format: 'docx' | 'pdf') { setBusy(format); setError(''); try { await downloadPracticeDraft(matterId, recordId, versionId, format); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(''); } }
  return <div><div className="button-group">{(['docx', 'pdf'] as const).map((format) => <button key={format} className="text-button" disabled={Boolean(busy)} onClick={() => void download(format)}><Icon name="download" size={14} />{busy === format ? 'İndiriliyor…' : format === 'docx' ? 'Word · bu sürüm' : 'PDF · bu sürüm'}</button>)}</div>{error && <Notice error>{error}</Notice>}</div>;
}

function Playbooks({ matterId, library, adopted, canCurate, onSave, error }: { matterId: string; library: PracticeRecord[]; adopted: PracticeRecord[]; canCurate: boolean; onSave: () => Promise<void>; error?: string }) {
  const [editing, setEditing] = useState<PracticeRecord | 'new' | null>(null); const [selection, setSelection] = useState(''); const [purpose, setPurpose] = useState(''); const [busy, setBusy] = useState(false); const [localError, setLocalError] = useState('');
  const selected = library.find((item) => item.id === selection);
  async function adopt(event: FormEvent) { event.preventDefault(); if (!selected) return; setBusy(true); setLocalError(''); try { await post(`/matters/${encodeURIComponent(matterId)}/practice/playbooks`, { playbook_id: selected.id, version_id: selected.latest_version_id, purpose }); setSelection(''); setPurpose(''); await onSave(); } catch (cause) { setLocalError(messageOf(cause)); } finally { setBusy(false); } }
  return <><p>Kurum rehberleri, kurumun tercihleri ve çalışma yöntemleridir; hukuki otorite değildir. Dosyaya benimsenen sürüm sabitlenir, sonraki rehber değişiklikleri otomatik uygulanmaz.</p>{error && <Notice error>{error}</Notice>}{canCurate && <button className="text-button" onClick={() => setEditing(editing ? null : 'new')}><Icon name={editing ? 'close' : 'plus'} size={16} />{editing ? 'Rehber düzenleyicisini kapat' : 'Kurum rehberi yaz'}</button>}{editing && <PlaybookEditor key={editing === 'new' ? 'new' : editing.id} record={editing === 'new' ? undefined : editing} onCancel={() => setEditing(null)} onSave={async () => { setEditing(null); await onSave(); }} />}
    <Detail title={`Kurum kütüphanesi (${library.length})`}>{library.length ? library.map((record) => <article className="practice-record" key={record.id}><div className="practice-record-heading"><div><h3>{record.title}</h3><span className="small muted">{record.domain === 'general' ? 'Genel' : DOMAIN_LABELS[record.domain as keyof typeof DOMAIN_LABELS]} · Sürüm {record.version}</span></div><Badge>{STATUS[record.curation_status || 'draft']}</Badge></div><p className="authored-text">{record.text}</p>{record.curation_note && <p className="review-note"><strong>Kürasyon notu:</strong> {record.curation_note}</p>}{canCurate && <button className="text-button" onClick={() => setEditing(record)}><Icon name="edit" size={14} />Yeni sürüm yaz</button>}<VersionHistory endpoint={`/playbooks/${encodeURIComponent(record.id)}/versions`} /></article>) : <p className="small muted">Henüz kurum rehberi yok. Yetkili küratör veya yönetici, açıkça insan tarafından yazılmış bir rehber ekleyebilir.</p>}</Detail>
    {library.some((record) => record.curation_status === 'curated') && <form className="inline-form form-grid" onSubmit={adopt}><Field label="Dosyada kullanılacak rehber sürümü" className="span-full">{(id) => <select id={id} required value={selection} onChange={(event) => setSelection(event.target.value)}><option value="">İncelenmiş bir sürüm seçin</option>{library.filter((record) => record.curation_status === 'curated').map((record) => <option key={record.id} value={record.id}>{record.title} · Sürüm {record.version}</option>)}</select>}</Field>{selected && <div className="span-full"><p className="authored-text selected-playbook-text">{selected.text}</p><p className="small muted">Yukarıdaki metnin sürüm {selected.version} kaydı bu dosyada sabitlenecek.</p></div>}<Field label="Bu dosyada kullanım amacı" className="span-full">{(id) => <textarea id={id} required minLength={3} maxLength={2000} rows={2} value={purpose} onChange={(event) => setPurpose(event.target.value)} />}</Field>{localError && <div className="span-full"><Notice error>{localError}</Notice></div>}<div className="form-actions span-full"><button className="button primary" disabled={busy || !selected}>{busy ? 'Kaydediliyor…' : 'Bu sürümü dosyada benimse'}</button></div></form>}
    <h3>Dosyada benimsenen rehber sürümleri</h3>{adopted.length ? adopted.map((record) => <article className="practice-record" key={record.id}><div className="practice-record-heading"><h3>{record.title} · Sürüm {record.version}</h3><Badge>Kurum tercihi</Badge></div><p><strong>Kullanım amacı:</strong> {record.purpose}</p><Detail title="Benimsenen değişmez metin"><p className="authored-text">{record.text}</p><p className="reference-id">{record.version_id}</p></Detail></article>) : <p className="practice-empty">Bu dosyada henüz bir rehber sürümü benimsenmedi.</p>}
  </>;
}

function PlaybookEditor({ record, onCancel, onSave }: { record?: PracticeRecord; onCancel: () => void; onSave: () => Promise<void> }) {
  const [form, setForm] = useState({ title: record?.title || '', domain: record?.domain || 'general', text: record?.text || '', curation_status: record?.curation_status || 'draft', curation_note: record?.curation_note || '', change_note: '' });
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const update = (key: keyof typeof form, value: string) => setForm((old) => ({ ...old, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await post(record ? `/playbooks/${encodeURIComponent(record.id)}/versions` : '/playbooks', { ...form, ...(record ? { expected_revision: record.revision } : {}) }); await onSave(); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  return <form className="inline-form form-grid" onSubmit={submit}><div className="span-full"><h3>{record ? `Rehber · Yeni sürüm ${record.version + 1}` : 'Kurum rehberi oluştur'}</h3><p className="small muted">Bu içerik kurum kullanıcılarıyla paylaşılır. Dosyaya ait gizli bilgiler otomatik taşınmaz; yalnızca paylaşılmasına yetkili olduğunuz genel çalışma tercihlerini yazın.</p></div>{error && <div className="span-full"><Notice error>{error}</Notice></div>}<Field label="Rehber başlığı" className="span-full">{(id) => <input id={id} required maxLength={200} value={form.title} onChange={(event) => update('title', event.target.value)} />}</Field><Field label="Uygulama alanı">{(id) => <select id={id} value={form.domain} onChange={(event) => update('domain', event.target.value)}><option value="general">Genel</option>{Object.entries(DOMAIN_LABELS).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select>}</Field><Field label="Kürasyon durumu">{(id) => <select id={id} value={form.curation_status} onChange={(event) => update('curation_status', event.target.value)}>{['draft', 'curated', 'retired'].map((value) => <option key={value} value={value}>{STATUS[value]}</option>)}</select>}</Field><Field label="İnsan tarafından yazılmış kurum tercihi" className="span-full">{(id) => <textarea id={id} required maxLength={20000} rows={7} value={form.text} onChange={(event) => update('text', event.target.value)} />}</Field><Field label="Küratörün inceleme notu" className="span-full">{(id) => <textarea id={id} required={form.curation_status === 'curated'} minLength={form.curation_status === 'curated' ? 3 : undefined} maxLength={2000} rows={2} value={form.curation_note} onChange={(event) => update('curation_note', event.target.value)} />}</Field>{record && <Field label="Sürüm değişikliği gerekçesi" className="span-full">{(id) => <textarea id={id} required minLength={3} maxLength={2000} rows={2} value={form.change_note} onChange={(event) => update('change_note', event.target.value)} />}</Field>}<div className="form-actions span-full"><button type="button" className="button secondary" onClick={onCancel}>Vazgeç</button><button className="button primary" disabled={busy}>{busy ? 'Kaydediliyor…' : 'Rehber sürümünü kaydet'}</button></div></form>;
}
