import { useEffect, useState, type FormEvent } from 'react';
import { post, request } from '../../api';
import { Empty, Field, Loading, Notice } from '../../components';
import type { WorkspaceComment } from '../../types';
import { formatDate, messageOf } from '../../utils';
export default function WorkspaceComments({ workspaceId }: { workspaceId: string }) {
  const [comments, setComments] = useState<WorkspaceComment[]>([]); const [loading, setLoading] = useState(true); const [text, setText] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); request<WorkspaceComment[]>(`/workspaces/${encodeURIComponent(workspaceId)}/comments`, { signal: controller.signal }).then(setComments).catch(cause => { if (cause.name !== 'AbortError') setError(messageOf(cause)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [workspaceId]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const comment = await post<WorkspaceComment>(`/workspaces/${encodeURIComponent(workspaceId)}/comments`, { text: text.trim() }); setComments(previous => [...previous, comment]); setText(''); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  return <section><div className="section-heading"><div><h2>Yorumlar</h2><p className="small muted">İş birliği notları ve çalışma kararları. Yorumlar hukuki dayanak yerine geçmez.</p></div><span className="count">{comments.length}</span></div>{error && <Notice error>{error}</Notice>}<form className="comment-compose" onSubmit={submit}><Field label="Yeni yorum" hint="Kaydedilen yorumlar geçmişi korumak için değiştirilemez. Düzeltme gerektiğinde yeni yorum ekleyin.">{id => <textarea id={id} rows={4} required maxLength={10000} value={text} onChange={event => setText(event.target.value)} placeholder="Çalışma hakkında bir not veya sonraki adımı paylaşın…" />}</Field><div className="form-actions"><button className="button primary" disabled={busy || !text.trim()}>{busy ? 'Kaydediliyor…' : 'Yorumu ekle'}</button></div></form>{loading ? <Loading label="Yorumlar yükleniyor…" /> : comments.length ? <div className="comment-timeline">{comments.map(comment => <article key={comment.id}><header><strong>{comment.author_name}</strong><time dateTime={comment.created_at}>{formatDate(comment.created_at)} · {new Date(comment.created_at).toLocaleTimeString('tr-TR', { timeZone: 'Europe/Istanbul', hour: '2-digit', minute: '2-digit' })}</time></header><p>{comment.text}</p></article>)}</div> : <Empty title="Henüz yorum eklenmedi.">İlk notu yazarak çalışma geçmişini başlatın.</Empty>}</section>;
}
