Foreground yes
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
TCPSocket 3310
TCPAddr 0.0.0.0
LogFile /tmp/clamd.log
LogFileMaxSize 1M
LogTime no
LogClean no
LogVerbose no
LogSyslog no
PidFile /tmp/clamd.pid
OfficialDatabaseOnly yes
SelfCheck 0
ConcurrentDatabaseReload no
MaxThreads 2
MaxQueue 4
ReadTimeout 10
CommandReadTimeout 5
SendBufTimeout 5000
StreamMaxLength 20M
MaxFileSize 20M
MaxScanSize 100M
MaxScanTime 20000
MaxRecursion 12
MaxFiles 5000
AlertExceedsMax yes
AlertEncrypted yes
AlertBrokenExecutables yes
HeuristicAlerts yes
ScanArchive yes
ScanPDF yes
ScanOLE2 yes
ScanHTML yes
Bytecode yes
BytecodeSecurity TrustSigned
BytecodeTimeout 10000
DisableCache yes
