import { useEffect, useRef, useState, type FormEvent } from 'react';
import { request } from '../api';
import { Detail, Icon, Notice } from '../components';
import type { AssistantMode, AssistantResponse, SystemStatus } from '../types';
import { formatDate, messageOf } from '../utils';
import { safeAppHref, usePortfolio } from './portfolio';

const MODE_LABELS: Record<AssistantMode, string> = { guide: 'Kullanım rehberi', chat: 'Asistana sor', daily: 'Günlük özet', weekly: 'Haftalık özet', monthly: 'Aylık özet' };
const SECTION_LABELS: Record<string, string> = { overview: 'Genel bakış', documents: 'Dosyalar', facts: 'Olgular', practice: 'Çalışma notları', research: 'Araştırma', comments: 'Yorumlar' };
interface Entry { id: number; question: string; response: AssistantResponse; contextLabel: string; revision: number }
export default function AssistantPanel({ workspaceId, page, section }: { workspaceId: string | null; page: string; section: string }) {
  const { filters, workspaces, customers, revision } = usePortfolio();
  const [question, setQuestion] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [entries, setEntries] = useState<Entry[]>([]);
  const [status, setStatus] = useState<SystemStatus | null>(null);
  useEffect(() => { const abort = new AbortController(); request<SystemStatus>('/status', { signal: abort.signal }).then(setStatus).catch(() => undefined); return () => abort.abort(); }, []);
  const [mode, setMode] = useState<AssistantMode>('chat'); const controller = useRef<AbortController | null>(null); const entryId = useRef(0);
  const activeWorkspace = workspaces.find(workspace => workspace.id === workspaceId);
  const contextLabel = workspaceId ? `${activeWorkspace?.title || 'Seçili çalışma alanı'} · ${SECTION_LABELS[section] || section}` : page === 'customers' ? 'Müvekkil portföyü' : page === 'graphs' ? 'Hukuk haritası' : page === 'sources' ? 'Kaynak incelemesi · kullanım rehberi' : page === 'coverage' ? 'Kaynak kapsamı' : page === 'system' ? 'Sistem durumu' : 'Çalışma alanı portföyü';
  const filterLabel = filters.customer_ids.length ? customers.filter(customer => filters.customer_ids.includes(customer.id)).map(customer => customer.name).join(', ') : 'Tüm yetkili müvekkiller';
  const contextKey = JSON.stringify([workspaceId, page, section, filters]);
  // A late response must not be shown under a different workspace or portfolio filter.
  useEffect(() => { controller.current?.abort(); setBusy(false); setError(''); }, [contextKey]);
  useEffect(() => () => controller.current?.abort(), []);
  async function send(selectedMode: AssistantMode, text = question) {
    if (busy || (selectedMode === 'chat' && !text.trim())) return;
    const abort = new AbortController(); controller.current = abort; setBusy(true); setError(''); setMode(selectedMode);
    try {
      const response = await request<AssistantResponse>('/assistant/respond', { method: 'POST', signal: abort.signal, body: JSON.stringify({ mode: selectedMode, question: text.trim(), context: { workspace_id: workspaceId, page, section, customer_ids: filters.customer_ids, date_from: filters.date_from || null, date_to: filters.date_to || null, date_field: filters.date_field } }) });
      if (!abort.signal.aborted) { setEntries(previous => [...previous.slice(-11), { id: ++entryId.current, question: text.trim() || MODE_LABELS[selectedMode], response, contextLabel: `${contextLabel} · ${filterLabel}${filters.date_from || filters.date_to ? ` · ${formatDate(filters.date_from)} — ${formatDate(filters.date_to)}` : ''}`, revision }]); setQuestion(''); }
    } catch (cause) { if (!abort.signal.aborted) setError(messageOf(cause)); } finally { if (controller.current === abort) setBusy(false); }
  }
  function submit(event: FormEvent) { event.preventDefault(); void send('chat'); }
  return <div className="assistant-panel"><div className="assistant-context"><span className="eyebrow">ŞİMDİKİ BAĞLAM</span><strong>{contextLabel}</strong><p>{filterLabel}</p>{(filters.date_from || filters.date_to) && <p>{formatDate(filters.date_from)} — {formatDate(filters.date_to)}</p>}{page === 'sources' && <p className="small muted">Bu ekranda yalnızca kullanım rehberi verilir; kaynak metni ve inceleme notları asistana aktarılmaz.</p>}<span className="context-indicator"><span />Seçiminizle güncellenir</span></div>
    <div className="assistant-shortcuts"><button type="button" onClick={() => void send('guide', '')} disabled={busy}><Icon name="book" size={16} />Bu ekranda nasıl ilerlerim?<Icon name="arrow" size={15} /></button><div className="summary-shortcuts" aria-label="Portföy özeti dönemi">{(['daily', 'weekly', 'monthly'] as const).map(period => <button key={period} disabled={busy} onClick={() => void send(period, '')}>{period === 'daily' ? 'Günlük' : period === 'weekly' ? 'Haftalık' : 'Aylık'}<span>Portföy özeti</span></button>)}</div></div>
    <div className="assistant-conversation" aria-live="polite" aria-busy={busy}>{!entries.length && <div className="assistant-welcome"><span className="assistant-monogram" aria-hidden="true">H.</span><h2>Bir sonraki adım,<br /><em>birlikte.</em></h2><p>Çalışma alanınızı düzenlerken yol gösterebilirim. Portföy özetleri seçili müvekkil ve tarih filtrelerinizi kullanır.</p><p className="small muted">Yanıtlar yalnızca yetkili olduğunuz kayıtları temel alır. Hukuki değerlendirmeyi kaynaklarıyla birlikte inceleyin.</p></div>}{entries.map(entry => <article className="assistant-entry" key={entry.id}><p className="assistant-question">{entry.question}</p><div className="assistant-answer"><div className="assistant-answer-meta"><span>{MODE_LABELS[entry.response.mode] || 'Asistan'}</span><span>{entry.response.provider_used ? 'Yerel yapay zekâ' : 'Kayıt / rehber yanıtı'}</span></div><p className="response-context">{entry.contextLabel}</p>{entry.revision !== revision && <p className="context-stale">Bu yanıttan sonra kayıtlar değişti. Güncel değerlendirme için yeniden sorun.</p>}<p className="answer-text">{entry.response.answer}</p>{entry.response.period && <p className="small muted">Dönem: {formatDate(entry.response.period.from)} — {formatDate(entry.response.period.to)}</p>}{entry.response.suggestions?.length > 0 && <div className="assistant-suggestions">{entry.response.suggestions.map((suggestion, index) => { const href = safeAppHref(suggestion.href); return href ? <a href={href} key={index}>{suggestion.label}<Icon name="arrow" size={13} /></a> : <span key={index}>{suggestion.label}</span>; })}</div>}{entry.response.sources?.length > 0 && <Detail title={`Dayanak kayıtları (${entry.response.sources.length})`}><ul>{entry.response.sources.map(source => { const href = safeAppHref(source.href) || (source.workspace_id ? `#/matters/${encodeURIComponent(source.workspace_id)}` : null); return <li key={source.id}>{href ? <a className="text-link" href={href}>{source.label}</a> : source.label}</li>; })}</ul></Detail>}{entry.response.limitations?.length > 0 && <Detail title="Kapsam ve sınırlamalar"><ul>{entry.response.limitations.map((limitation, index) => <li key={index}>{limitation}</li>)}</ul></Detail>}</div></article>)}{busy && <div className="assistant-working" role="status"><span className="spinner" />{MODE_LABELS[mode]} hazırlanıyor…<button className="text-button" onClick={() => { controller.current?.abort(); setBusy(false); }}>Durdur</button></div>}{error && <Notice error>{error}</Notice>}</div>
    <form className="assistant-compose" onSubmit={submit}><>{status?.provider.readiness && !status.provider.readiness.configuration_ready && <p className="assistant-readiness">Yerel dil modeli bağlantısı hazır değil. Rehber ve kayıt tabanlı portföy özetleri kullanılabilir. <a className="text-link" href="#/system">Ayarları incele</a></p>}</><label htmlFor="assistant-question">Asistana sorun</label><textarea id="assistant-question" rows={3} maxLength={2000} value={question} onChange={event => setQuestion(event.target.value)} placeholder="Bu çalışma alanında nasıl ilerleyebilirim?" /><div><span>Yerel hizmet · Avukat denetiminde</span><button className="button primary" disabled={busy || !question.trim()} type="submit" aria-label="Asistana gönder"><Icon name="arrow" size={17} /></button></div>{entries.length > 0 && <button className="text-button clear-chat" type="button" disabled={busy} onClick={() => setEntries([])}>Görüşmeyi temizle</button>}</form>
  </div>;
}
