import { useState, type FormEvent } from 'react';
import { post } from '../api';
import { Empty, Field, Icon, Loading, Notice, PageHeader } from '../components';
import { usePortfolio } from '../workbench/portfolio';
import { messageOf } from '../utils';
export default function CustomersPage() {
  const { customers, filters, setFilters, loading } = usePortfolio();
  const [adding, setAdding] = useState(false); const [name, setName] = useState(''); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError('');
    try { await post('/customers', { name: name.trim(), notes: notes.trim() }); setName(''); setNotes(''); setAdding(false); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); }
  }
  return <><PageHeader eyebrow="MÜVEKKİL PORTFÖYÜ" title="İlişkileri bir arada tutun." description="Bir müvekkil birden fazla çalışma alanına bağlanabilir. Bir çalışma alanını birden fazla müvekkille ilişkilendirebilirsiniz." action={<button className="button primary" onClick={() => setAdding(!adding)}><Icon name={adding ? 'close' : 'plus'} size={17} />{adding ? 'Formu kapat' : 'Müvekkil ekle'}</button>} />{error && <Notice error>{error}</Notice>}{adding && <form className="inline-form" onSubmit={submit}><Field label="Müvekkil adı">{id => <input id={id} required autoFocus maxLength={200} value={name} onChange={event => setName(event.target.value)} placeholder="Kişi veya kuruluş adı" />}</Field><Field label="Not" hint="İsteğe bağlı. Yalnızca yetkili portföy kullanıcıları görür.">{id => <textarea id={id} rows={3} maxLength={4000} value={notes} onChange={event => setNotes(event.target.value)} />}</Field><div className="form-actions"><button className="button secondary" type="button" onClick={() => setAdding(false)}>Vazgeç</button><button className="button primary" disabled={busy || !name.trim()}>{busy ? 'Kaydediliyor…' : 'Müvekkili kaydet'}</button></div></form>}
    <div className="section-heading"><h2>Müvekkiller <span className="count">{customers.length}</span></h2><span className="small muted">Çalışma alanlarıyla bağlantılı portföy</span></div>{loading && !customers.length ? <Loading /> : !customers.length ? <Empty title="İlk müvekkilinizi ekleyin.">Ardından yeni veya mevcut çalışma alanlarını müvekkillerinizle ilişkilendirin.</Empty> : <div className="customer-register">{customers.map((customer, index) => <article key={customer.id}><span className="matter-number">{String(index + 1).padStart(2, '0')}</span><div><h3>{customer.name}</h3>{customer.notes && <p>{customer.notes}</p>}{customer.workspace_count !== undefined && <span className="small muted">{customer.workspace_count} çalışma alanı</span>}</div><button className="text-button" onClick={() => { setFilters({ ...filters, customer_ids: [customer.id] }); window.location.hash = '/matters'; }}>Çalışmalar<Icon name="arrow" size={16} /></button></article>)}</div>}</>;
}
