import { ValidityDetails } from '../ValidityDetails';
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { request } from '../api';
import { Badge, Detail, Empty, Field, Icon, JsonDetails, Loading, Notice, PageHeader } from '../components';
import type { GraphCatalog, GraphNode, GraphResult } from '../types';
import { messageOf, statusLabel } from '../utils';

const graphLimitationLabels: Record<string, string> = {
  'Ontology schema only: no real institutional or historical records are loaded, and synthetic fixtures are never exposed.': 'Yalnızca ontoloji şeması: gerçek kurum veya tarihsel kayıt yüklenmemiştir. Kurgusal test verileri bu görünümde yayımlanmaz.',
  'An as-of date does not turn ontology categories into historical legal evidence.': 'Tarih filtresi seçmek, ontoloji kategorilerini tarihsel hukuki kanıta dönüştürmez.',
};

export default function GraphPage() {
  const [catalog, setCatalog] = useState<GraphCatalog | null>(null); const [graph, setGraph] = useState<'structure' | 'jurisprudence'>('structure');
  const [query, setQuery] = useState(''); const [asOf, setAsOf] = useState(''); const [result, setResult] = useState<GraphResult | null>(null);
  const [selected, setSelected] = useState<GraphNode | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState('');
  const activeRequest = useRef<AbortController | null>(null);
  async function explore(nextGraph = graph, nextQuery = query) {
    activeRequest.current?.abort(); const controller = new AbortController(); activeRequest.current = controller;
    setBusy(true); setError(''); setSelected(null); setResult(null);
    const params = new URLSearchParams({ graph: nextGraph, query: nextQuery, limit: '30', ...(asOf ? { as_of: asOf } : {}) });
    try { const data = await request<GraphResult>(`/graphs/explore?${params}`, { signal: controller.signal }); if (!controller.signal.aborted) setResult(data); } catch (cause) { if (!controller.signal.aborted) setError(messageOf(cause)); } finally { if (!controller.signal.aborted) setBusy(false); }
  }
  useEffect(() => { const controller = new AbortController(); request<GraphCatalog>('/graphs/catalog', { signal: controller.signal }).then(setCatalog).catch((cause) => { if (!controller.signal.aborted) setError(messageOf(cause)); }); void explore('structure', ''); return () => { controller.abort(); activeRequest.current?.abort(); }; }, []);
  function submit(event: FormEvent) { event.preventDefault(); void explore(); }
  function switchGraph(value: 'structure' | 'jurisprudence') { setGraph(value); void explore(value); }
  return <>
    <PageHeader eyebrow="İLİŞKİLER VE REFERANSLAR" title="Hukukun içindeki yerini bulun." description="Kavramları, normları ve içtihat bağlantılarını inceleyin. Harita, belgeye dayalı değerlendirmenin başlangıç noktasıdır." />
    <div className="graph-mode-tabs"><button className={graph === 'structure' ? 'active' : ''} aria-pressed={graph === 'structure'} onClick={() => switchGraph('structure')}><Icon name="graph" size={18} /><span>Hukuk yapısı<small>Kavram, kurum ve normlar</small></span></button><button className={graph === 'jurisprudence' ? 'active' : ''} aria-pressed={graph === 'jurisprudence'} onClick={() => switchGraph('jurisprudence')}><Icon name="book" size={18} /><span>İçtihat ağı<small>Kararlar ve tarihsel ilişkiler</small></span></button></div>
    {catalog && <div className="graph-status-line"><Badge status={catalog.review_status} /><span>Sürüm {catalog.version}</span><a className="text-link" href="#/coverage">Kapsamı değerlendir<Icon name="arrow" size={15} /></a></div>}
    <form className="graph-search" onSubmit={submit}><Field label="Kavram veya referans ara">{(id) => <div className="search-input"><Icon name="search" size={18} /><input id={id} placeholder="Örn. Sözleşmeler, iş hukuku, mahkeme…" value={query} onChange={(event) => setQuery(event.target.value)} /></div>}</Field><Field label="Tarih filtresi">{(id) => <input id={id} type="date" value={asOf} onChange={(event) => setAsOf(event.target.value)} />}</Field><button className="button primary" disabled={busy}>{busy ? 'Aranıyor…' : 'Haritada ara'}<Icon name="arrow" size={17} /></button></form>
    {error && <Notice error>{error}</Notice>}
    {result?.limitations?.length ? <Detail title="Bu görünümün sınırları" open><ul>{result.limitations.map((item, index) => <li key={index}>{graphLimitationLabels[item] || item}</li>)}</ul></Detail> : null}
    <div className="graph-workspace"><section className="graph-canvas" aria-label="Hukuk ilişkileri haritası"><div className="graph-canvas-heading"><span className="small-label">{graph === 'structure' ? 'YAPISAL HARİTA' : 'TARİHSEL İÇTİHAT AĞI'}</span>{result && <span>{result.nodes.length} düğüm · {result.edges.length} ilişki</span>}</div>{busy ? <Loading label="İlişkiler yükleniyor…" /> : result?.nodes.length ? <GraphDrawing result={result} selected={selected?.id} onSelect={setSelected} /> : <Empty title={graph === 'jurisprudence' ? 'Bu kapsamda karar bağlantısı yok.' : 'Bu aramada bağlantı bulunamadı.'}>{graph === 'jurisprudence' ? 'Yayımlanmış kararlar ve incelenmiş ilişkiler eklendiğinde burada görünür. Boş görünüm, emsal olmadığı anlamına gelmez.' : 'Aramayı genişletin veya başka bir hukuk dalı seçin. Katalog kapsamı ile hukuki geçerlilik farklı değerlendirilir.'}</Empty>}<div className="graph-caption">Bir düğüm seçerek türünü, inceleme durumunu ve kayıtlı ilişkilerini görün.</div></section><aside className="graph-inspector">{selected && result ? <NodeInspector node={selected} result={result} onSelect={setSelected} /> : <><p className="eyebrow">KAVRAMDAN KAYNAĞA</p><h2>Bağlantının<br />anlamı önemlidir.</h2><p>Bir atıf, onay veya bağlayıcılık anlamına gelmez. İlişki türünü ve dayanağını ayrı ayrı inceleyin.</p><div className="graph-reading-key"><span className="graph-key-line" />Kayıtlı yönlü ilişki</div><div className="graph-reading-key"><span className="graph-key-node" />İnceleme durumu düğüm ayrıntısında</div></>}</aside></div>
    {catalog && <div className="graph-catalog"><section><div className="section-heading"><h2>Hukuk alanları</h2><span className="small muted">Katalogdaki {catalog.domains.length} alan</span></div><div className="domain-index">{catalog.domains.map((domain) => <button key={domain.id} onClick={() => { setQuery(domain.label); setGraph('structure'); void explore('structure', domain.label); }}><span>{domain.label}</span><Icon name="arrow" size={15} /></button>)}</div></section><Detail title={`Ontoloji sınıfları ve ilişki sözlüğü (${catalog.classes.length} sınıf, ${catalog.relations.length} ilişki)`}><div className="two-column-details"><section><h3>Sınıflar</h3><dl className="catalog-definitions">{catalog.classes.map((item) => <div key={item.id}><dt>{item.label}</dt><dd>{item.module}</dd></div>)}</dl></section><section><h3>İlişkiler</h3><dl className="catalog-definitions">{catalog.relations.map((item) => <div key={item.id}><dt>{item.label}</dt><dd>{item.requires_legal_review ? 'Hukuki inceleme gerekli' : 'Yapısal ilişki'}<span className="reference-id">{item.id}</span></dd></div>)}</dl></section></div></Detail></div>}
    {result && <JsonDetails value={result.snapshot} title="Harita sürümü ve veri kaydı" />}
  </>;
}

function NodeInspector({ node, result, onSelect }: { node: GraphNode; result: GraphResult; onSelect: (node: GraphNode) => void }) {
  const edges = result.edges.filter((edge) => edge.source === node.id || edge.target === node.id);
  return <><p className="eyebrow">SEÇİLİ DÜĞÜM</p><h2>{node.label}</h2><Badge status={node.review_status} /><dl className="inspector-meta"><div><dt>Tür</dt><dd>{statusLabel(node.type)}</dd></div><div><dt>Graf</dt><dd>{node.graph === 'structure' ? 'Hukuk yapısı' : node.graph === 'jurisprudence' ? 'İçtihat ağı' : node.graph}</dd></div></dl><h3>Kayıtlı ilişkiler</h3>{edges.length ? <div className="relation-list">{edges.map((edge) => { const outgoing = edge.source === node.id; const other = result.nodes.find((item) => item.id === (outgoing ? edge.target : edge.source)); return <div className="relation" key={edge.id}><span className="small-label">{outgoing ? 'BU DÜĞÜMDEN' : 'BU DÜĞÜME'}</span><strong>{statusLabel(edge.label)}</strong>{other ? <button className="text-button" onClick={() => onSelect(other)}>{other.label}<Icon name="arrow" size={14} /></button> : <span className="reference-id">{outgoing ? edge.target : edge.source}</span>}<span className="small muted">{statusLabel(edge.status)}</span><ValidityDetails validity={edge} />{edge.evidence_id && <Detail title="Dayanak kimliği"><span className="reference-id">{edge.evidence_id}</span><p className="small muted">Kimlik, kaynağın incelendiği anlamına gelmez.</p></Detail>}</div>; })}</div> : <p className="small muted">Bu görünümde bağlantı bulunmuyor.</p>}<Detail title="Kalıcı kimlik"><span className="reference-id">{node.id}</span></Detail></>;
}

function GraphDrawing({ result, selected, onSelect }: { result: GraphResult; selected?: string; onSelect: (node: GraphNode) => void }) {
  const layout = useMemo(() => {
    const depths = new Map<string, number>(); const nodeIds = new Set(result.nodes.map((node) => node.id));
    const targets = new Set(result.edges.filter((edge) => nodeIds.has(edge.source)).map((edge) => edge.target));
    const roots = result.nodes.filter((node) => !targets.has(node.id));
    const queue = (roots.length ? roots : result.nodes.slice(0, 1)).map((node) => ({ id: node.id, depth: 0 }));
    while (queue.length) { const item = queue.shift()!; if (depths.has(item.id)) continue; depths.set(item.id, Math.min(item.depth, 3)); result.edges.filter((edge) => edge.source === item.id && nodeIds.has(edge.target)).forEach((edge) => queue.push({ id: edge.target, depth: item.depth + 1 })); }
    result.nodes.filter((node) => !depths.has(node.id)).forEach((node, index) => depths.set(node.id, index % 3));
    const columns = new Map<number, GraphNode[]>(); result.nodes.forEach((node) => { const depth = depths.get(node.id)!; columns.set(depth, [...(columns.get(depth) || []), node]); });
    const height = Math.max(390, ...Array.from(columns.values()).map((nodes) => nodes.length * 76 + 80));
    const positions = new Map<string, { x: number; y: number }>();
    columns.forEach((nodes, depth) => nodes.forEach((node, index) => positions.set(node.id, { x: 132 + depth * 234, y: 48 + (index + 0.5) * ((height - 96) / nodes.length) })));
    return { positions, height, width: Math.max(740, 260 + Math.max(...columns.keys()) * 234) };
  }, [result]);
  return <div className="graph-scroll"><svg className="graph-svg" viewBox={`0 0 ${layout.width} ${layout.height}`} role="group" aria-label="Düğümler ve yönlü ilişkiler"><defs><marker id="graph-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" /></marker></defs>{result.edges.map((edge) => { const from = layout.positions.get(edge.source); const to = layout.positions.get(edge.target); if (!from || !to) return null; const isRelated = edge.source === selected || edge.target === selected; const horizontal = Math.abs(to.x - from.x) > 100; const startX = from.x + (horizontal ? (to.x > from.x ? 92 : -92) : 0); const targetX = to.x + (horizontal ? (to.x > from.x ? -96 : 96) : 0); const startY = from.y + (horizontal ? 0 : (to.y > from.y ? 23 : -23)); const targetY = to.y + (horizontal ? 0 : (to.y > from.y ? -26 : 26)); return <path key={edge.id} className={`graph-edge ${isRelated ? 'related' : ''}`} d={`M${startX},${startY} C${(startX + targetX) / 2},${startY} ${(startX + targetX) / 2},${targetY} ${targetX},${targetY}`} markerEnd="url(#graph-arrow)"><title>{edge.label} · {statusLabel(edge.status)}</title></path>; })}{result.nodes.map((node) => { const pos = layout.positions.get(node.id)!; return <g key={node.id} role="button" tabIndex={0} aria-label={`${node.label}, ${statusLabel(node.review_status)}. Ayrıntıları göster.`} aria-pressed={selected === node.id} className={`graph-node ${selected === node.id ? 'selected' : ''}`} transform={`translate(${pos.x},${pos.y})`} onClick={() => onSelect(node)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(node); } }}><title>{node.label}</title><rect x="-92" y="-24" width="184" height="48" rx="3" /><circle cx="-77" cy="0" r="3" /><text x="-63" y="4">{node.label.length > 23 ? `${node.label.slice(0, 22)}…` : node.label}</text></g>; })}</svg></div>;
}
