import { useEffect, useState, type FormEvent } from 'react';
import { post } from '../api';
import { Badge, Empty, Field, Icon, Loading, Notice, PageHeader } from '../components';
import type { Domain, Matter } from '../types';
import { usePortfolio } from '../workbench/portfolio';
import { DOMAIN_LABELS, formatDate, messageOf } from '../utils';

export default function MattersPage({ newRequested = false }: { newRequested?: boolean }) {
  const { workspaces: matters, loading, error, refresh: load, filters } = usePortfolio();
  const [query, setQuery] = useState(''); const [domain, setDomain] = useState('all'); const [creating, setCreating] = useState(newRequested);
  useEffect(() => { setCreating(newRequested); }, [newRequested]);
  const filtered = matters.filter((matter) => (domain === 'all' || matter.domain === domain) && `${matter.title} ${matter.objective} ${matter.represented_party}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));
  return <>
    <PageHeader eyebrow="ÇALIŞMA ALANLARI" title="Hazırlığın başlangıç noktası." description="Belgelerinizi bir araya getirin, olguları netleştirin ve kaynaklara dayalı çalışmanızı oluşturun." action={<button className="button primary" onClick={() => setCreating(!creating)}><Icon name={creating ? 'close' : 'plus'} size={18} />{creating ? 'Formu kapat' : 'Yeni çalışma alanı'}</button>} />
    {creating && <NewMatter onCancel={() => setCreating(false)} onCreate={(matter) => { window.location.hash = `/matters/${encodeURIComponent(matter.id)}`; }} />}
    <p className="portfolio-scope-note">{filters.customer_ids.length ? `${filters.customer_ids.length} müvekkil seçili` : 'Tüm yetkili müvekkiller'} · Dosyalar, yüklendikleri çalışma alanında tutulur.</p><div className="matter-index-layout"><section className="matter-index"><div className="section-heading"><h2>Çalışma alanlarınız <span className="count">{matters.length}</span></h2><span className="small muted">Soldaki portföy filtreleri geçerli</span></div><div className="filter-bar"><label className="search-input"><Icon name="search" size={18} /><input aria-label="Çalışma alanlarında ara" placeholder="Başlık, amaç veya taraf ara" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select aria-label="Hukuk alanına göre filtrele" value={domain} onChange={(event) => setDomain(event.target.value)}><option value="all">Tüm alanlar</option>{Object.entries(DOMAIN_LABELS).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></div>
    {error && <Notice error>{error} <button className="text-button" onClick={load}>Yeniden dene</button></Notice>}
    {loading ? <Loading /> : filtered.length ? <div className="matter-list">{filtered.map((matter, index) => <a className="matter-row" key={matter.id} href={`#/matters/${encodeURIComponent(matter.id)}`}><span className="matter-number">{String(index + 1).padStart(2, '0')}</span><div className="matter-row-content"><div className="matter-row-title"><h3>{matter.title}</h3><Badge status={matter.status} /></div><p>{matter.objective || 'Çalışma amacı henüz eklenmedi.'}</p><div className="matter-row-meta"><span>{DOMAIN_LABELS[matter.domain] || matter.domain}</span><span>{matter.document_count || 0} dosya</span>{matter.customers?.map(customer => <span key={customer.id}>{customer.name}</span>)}<span>{formatDate(matter.created_at)}</span></div></div><Icon name="arrow" size={20} /></a>)}</div> : <Empty title={matters.length ? 'Bu filtrelerle çalışma alanı bulunamadı.' : 'İlk çalışma alanınızı açın.'}>{matters.length ? 'Arama ifadesini veya alan filtresini değiştirin.' : 'Önce çalışmanızın amacını belirleyin. Belgeler, olgular ve araştırmalar aynı çalışma alanında bir arada kalır.'}</Empty>}
    </section><aside className="preparation-note"><p className="eyebrow">BİR ÇALIŞMA DÜZENİ</p><h2>Belgeden<br />hazırlığa.</h2><ol><li><span>01</span><div><strong>Dayanağı toplayın</strong><p>Belgeleri yükleyin ve çıkarılan metni kontrol edin.</p></div></li><li><span>02</span><div><strong>Olguyu ayırın</strong><p>Beyanları, belgelenmiş olguları ve varsayımları ayrı tutun.</p></div></li><li><span>03</span><div><strong>Yorumu inceleyin</strong><p>Kaynakları görün, eksikleri değerlendirin ve çıktıyı gözden geçirin.</p></div></li></ol><a className="text-link" href="#/coverage">Kaynak kapsamını incele<Icon name="arrow" size={16} /></a></aside></div>
  </>;
}

function NewMatter({ onCancel, onCreate }: { onCancel: () => void; onCreate: (matter: Matter) => void }) {
  const { customers, filters } = usePortfolio();
  const [customerIds, setCustomerIds] = useState<string[]>(filters.customer_ids);
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', domain: 'contracts' as Domain, objective: '', represented_party: '', stage: '', relevant_date: '' });
  const update = (key: keyof typeof form, value: string) => setForm((prev) => ({ ...prev, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { onCreate(await post<Matter>('/workspaces', { ...form, customer_ids: customerIds, relevant_date: form.relevant_date || null })); } catch (cause) { setError(messageOf(cause)); } finally { setBusy(false); } }
  return <section className="creation-panel"><div className="creation-intro"><p className="eyebrow">YENİ ÇALIŞMA ALANI</p><h2>Önce amacı<br />netleştirelim.</h2><p>Bu bilgiler çalışma bağlamını oluşturur. Henüz bilinmeyen ayrıntıları boş bırakabilirsiniz.</p></div><form onSubmit={submit} className="form-grid">{error && <div className="span-full"><Notice error>{error}</Notice></div>}<Field label="Çalışma alanı adı" className="span-full">{(id) => <input id={id} autoFocus required maxLength={200} placeholder="Örn. Tedarik sözleşmesi incelemesi" value={form.title} onChange={(event) => update('title', event.target.value)} />}</Field><fieldset className="customer-selection span-full"><legend>İlişkili müvekkiller</legend><p className="field-hint">Birden fazla müvekkil seçebilirsiniz.</p>{customers.length ? customers.map(customer => <label className="check-option" key={customer.id}><input type="checkbox" checked={customerIds.includes(customer.id)} onChange={event => setCustomerIds(previous => event.target.checked ? [...previous, customer.id] : previous.filter(id => id !== customer.id))} /><span>{customer.name}</span></label>) : <a className="text-link" href="#/customers">Önce müvekkil ekleyebilirsiniz</a>}</fieldset><Field label="Hukuk alanı">{(id) => <select id={id} value={form.domain} onChange={(event) => update('domain', event.target.value)}>{Object.entries(DOMAIN_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>}</Field><Field label="İlgili tarih" hint="Uygulanacak hukuk açısından önemli tarih.">{(id) => <input id={id} type="date" value={form.relevant_date} onChange={(event) => update('relevant_date', event.target.value)} />}</Field><Field label="Çalışmanın amacı" className="span-full">{(id) => <textarea id={id} required rows={3} placeholder="Hangi soruya yanıt arıyorsunuz, nasıl bir çıktı hazırlamak istiyorsunuz?" value={form.objective} onChange={(event) => update('objective', event.target.value)} />}</Field><Field label="Temsil edilen taraf">{(id) => <input id={id} placeholder="İsteğe bağlı" value={form.represented_party} onChange={(event) => update('represented_party', event.target.value)} />}</Field><Field label="Süreç aşaması">{(id) => <input id={id} placeholder="Örn. Sözleşme müzakeresi" value={form.stage} onChange={(event) => update('stage', event.target.value)} />}</Field><div className="form-actions span-full"><button type="button" className="button secondary" onClick={onCancel}>Vazgeç</button><button className="button primary" disabled={busy}>{busy ? 'Oluşturuluyor…' : 'Çalışma alanını oluştur'}<Icon name="arrow" size={18} /></button></div></form></section>;
}
